[package]
name = "nessie"
version = "0.1.0"
edition = "2021"

[dependencies]
assert_matches = "1.5.0"
bitflags = "2.6.0"
env_logger = "0.11.5"
log = "0.4.22"
pixels = "0.13"
winit = "0.28"
thiserror = "1.0"
