use std::fmt::Display;

use bitflags::bitflags;

pub trait Bus {
    fn read(&self, address: u16) -> u8;
    fn write(&mut self, address: u16, value: u8);

    fn read16(&self, address: u16) -> u16 {
        let lo = u16::from(self.read(address));
        let hi = u16::from(self.read(address + 1));
        return (hi << 8) | lo;
    }
}

impl Bus for [u8; 65536] {
    fn read(&self, address: u16) -> u8 {
        self[address as usize]
    }

    fn write(&mut self, address: u16, value: u8) {
        self[address as usize] = value;
    }
}

#[derive(Debug, Clone, Copy)]
enum Address {
    Implied,
    Absolute(u16),
}

impl Display for Address {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Absolute(address) => write!(f, "abs {:#04x}", address),
            Self::Implied => write!(f, "implied"),
        }
    }
}

#[derive(Debug, Copy, Clone)]
struct OpCode {
    execute: fn(&mut CPU, Address),
    addressing: fn(&mut CPU) -> Address,
    name: &'static str,
    addr_name: &'static str,
    cycles: u8,
}

// Autogenerated from opcode_table_generator.py
static OPCODE_TABLE: [OpCode; 256] = [
    OpCode {
        execute: CPU::brk,
        addressing: CPU::implied,
        name: "BRK",
        addr_name: "IMP",
        cycles: 7,
    },
    OpCode {
        execute: CPU::ora,
        addressing: CPU::indirect_x,
        name: "ORA",
        addr_name: "IZX",
        cycles: 6,
    },
    OpCode {
        execute: CPU::ora,
        addressing: CPU::indirect_x,
        name: "ORA",
        addr_name: "IZX",
        cycles: 6,
    },
    OpCode {
        execute: CPU::slo,
        addressing: CPU::indirect_x,
        name: "SLO",
        addr_name: "IZX",
        cycles: 8,
    },
    OpCode {
        execute: CPU::nop,
        addressing: CPU::zero_page,
        name: "NOP",
        addr_name: "ZP",
        cycles: 3,
    },
    OpCode {
        execute: CPU::ora,
        addressing: CPU::zero_page,
        name: "ORA",
        addr_name: "ZP",
        cycles: 3,
    },
    OpCode {
        execute: CPU::asl,
        addressing: CPU::zero_page,
        name: "ASL",
        addr_name: "ZP",
        cycles: 5,
    },
    OpCode {
        execute: CPU::slo,
        addressing: CPU::zero_page,
        name: "SLO",
        addr_name: "ZP",
        cycles: 5,
    },
    OpCode {
        execute: CPU::php,
        addressing: CPU::implied,
        name: "PHP",
        addr_name: "IMP",
        cycles: 3,
    },
    OpCode {
        execute: CPU::ora,
        addressing: CPU::immediate,
        name: "ORA",
        addr_name: "IMM",
        cycles: 2,
    },
    OpCode {
        execute: CPU::asl,
        addressing: CPU::implied,
        name: "ASL",
        addr_name: "IMP",
        cycles: 2,
    },
    OpCode {
        execute: CPU::anc,
        addressing: CPU::immediate,
        name: "ANC",
        addr_name: "IMM",
        cycles: 2,
    },
    OpCode {
        execute: CPU::nop,
        addressing: CPU::absolute,
        name: "NOP",
        addr_name: "ABS",
        cycles: 4,
    },
    OpCode {
        execute: CPU::ora,
        addressing: CPU::absolute,
        name: "ORA",
        addr_name: "ABS",
        cycles: 4,
    },
    OpCode {
        execute: CPU::asl,
        addressing: CPU::absolute,
        name: "ASL",
        addr_name: "ABS",
        cycles: 6,
    },
    OpCode {
        execute: CPU::slo,
        addressing: CPU::absolute,
        name: "SLO",
        addr_name: "ABS",
        cycles: 6,
    },
    OpCode {
        execute: CPU::bpl,
        addressing: CPU::relative,
        name: "BPL",
        addr_name: "REL",
        cycles: 2,
    },
    OpCode {
        execute: CPU::ora,
        addressing: CPU::indirect_y,
        name: "ORA",
        addr_name: "IZY",
        cycles: 5,
    },
    OpCode {
        execute: CPU::ora,
        addressing: CPU::indirect_y,
        name: "ORA",
        addr_name: "IZY",
        cycles: 5,
    },
    OpCode {
        execute: CPU::slo,
        addressing: CPU::indirect_y,
        name: "SLO",
        addr_name: "IZY",
        cycles: 8,
    },
    OpCode {
        execute: CPU::nop,
        addressing: CPU::zero_page_x,
        name: "NOP",
        addr_name: "ZPX",
        cycles: 4,
    },
    OpCode {
        execute: CPU::ora,
        addressing: CPU::zero_page_x,
        name: "ORA",
        addr_name: "ZPX",
        cycles: 4,
    },
    OpCode {
        execute: CPU::asl,
        addressing: CPU::zero_page_x,
        name: "ASL",
        addr_name: "ZPX",
        cycles: 6,
    },
    OpCode {
        execute: CPU::slo,
        addressing: CPU::zero_page_x,
        name: "SLO",
        addr_name: "ZPX",
        cycles: 6,
    },
    OpCode {
        execute: CPU::clc,
        addressing: CPU::implied,
        name: "CLC",
        addr_name: "IMP",
        cycles: 2,
    },
    OpCode {
        execute: CPU::ora,
        addressing: CPU::absolute_y,
        name: "ORA",
        addr_name: "ABY",
        cycles: 4,
    },
    OpCode {
        execute: CPU::nop,
        addressing: CPU::implied,
        name: "NOP",
        addr_name: "IMP",
        cycles: 2,
    },
    OpCode {
        execute: CPU::slo,
        addressing: CPU::absolute_y,
        name: "SLO",
        addr_name: "ABY",
        cycles: 7,
    },
    OpCode {
        execute: CPU::nop,
        addressing: CPU::absolute_x,
        name: "NOP",
        addr_name: "ABX",
        cycles: 4,
    },
    OpCode {
        execute: CPU::ora,
        addressing: CPU::absolute_x,
        name: "ORA",
        addr_name: "ABX",
        cycles: 4,
    },
    OpCode {
        execute: CPU::asl,
        addressing: CPU::absolute_x,
        name: "ASL",
        addr_name: "ABX",
        cycles: 7,
    },
    OpCode {
        execute: CPU::slo,
        addressing: CPU::absolute_x,
        name: "SLO",
        addr_name: "ABX",
        cycles: 7,
    },
    OpCode {
        execute: CPU::jsr,
        addressing: CPU::absolute,
        name: "JSR",
        addr_name: "ABS",
        cycles: 6,
    },
    OpCode {
        execute: CPU::and,
        addressing: CPU::indirect_x,
        name: "AND",
        addr_name: "IZX",
        cycles: 6,
    },
    OpCode {
        execute: CPU::and,
        addressing: CPU::indirect_x,
        name: "AND",
        addr_name: "IZX",
        cycles: 6,
    },
    OpCode {
        execute: CPU::rla,
        addressing: CPU::indirect_x,
        name: "RLA",
        addr_name: "IZX",
        cycles: 8,
    },
    OpCode {
        execute: CPU::bit,
        addressing: CPU::zero_page,
        name: "BIT",
        addr_name: "ZP",
        cycles: 3,
    },
    OpCode {
        execute: CPU::and,
        addressing: CPU::zero_page,
        name: "AND",
        addr_name: "ZP",
        cycles: 3,
    },
    OpCode {
        execute: CPU::rol,
        addressing: CPU::zero_page,
        name: "ROL",
        addr_name: "ZP",
        cycles: 5,
    },
    OpCode {
        execute: CPU::rla,
        addressing: CPU::zero_page,
        name: "RLA",
        addr_name: "ZP",
        cycles: 5,
    },
    OpCode {
        execute: CPU::plp,
        addressing: CPU::implied,
        name: "PLP",
        addr_name: "IMP",
        cycles: 4,
    },
    OpCode {
        execute: CPU::and,
        addressing: CPU::immediate,
        name: "AND",
        addr_name: "IMM",
        cycles: 2,
    },
    OpCode {
        execute: CPU::rol,
        addressing: CPU::implied,
        name: "ROL",
        addr_name: "IMP",
        cycles: 2,
    },
    OpCode {
        execute: CPU::anc,
        addressing: CPU::immediate,
        name: "ANC",
        addr_name: "IMM",
        cycles: 2,
    },
    OpCode {
        execute: CPU::bit,
        addressing: CPU::absolute,
        name: "BIT",
        addr_name: "ABS",
        cycles: 4,
    },
    OpCode {
        execute: CPU::and,
        addressing: CPU::absolute,
        name: "AND",
        addr_name: "ABS",
        cycles: 4,
    },
    OpCode {
        execute: CPU::rol,
        addressing: CPU::absolute,
        name: "ROL",
        addr_name: "ABS",
        cycles: 6,
    },
    OpCode {
        execute: CPU::rla,
        addressing: CPU::absolute,
        name: "RLA",
        addr_name: "ABS",
        cycles: 6,
    },
    OpCode {
        execute: CPU::bmi,
        addressing: CPU::relative,
        name: "BMI",
        addr_name: "REL",
        cycles: 2,
    },
    OpCode {
        execute: CPU::and,
        addressing: CPU::indirect_y,
        name: "AND",
        addr_name: "IZY",
        cycles: 5,
    },
    OpCode {
        execute: CPU::and,
        addressing: CPU::indirect_y,
        name: "AND",
        addr_name: "IZY",
        cycles: 5,
    },
    OpCode {
        execute: CPU::rla,
        addressing: CPU::indirect_y,
        name: "RLA",
        addr_name: "IZY",
        cycles: 8,
    },
    OpCode {
        execute: CPU::nop,
        addressing: CPU::zero_page_x,
        name: "NOP",
        addr_name: "ZPX",
        cycles: 4,
    },
    OpCode {
        execute: CPU::and,
        addressing: CPU::zero_page_x,
        name: "AND",
        addr_name: "ZPX",
        cycles: 4,
    },
    OpCode {
        execute: CPU::rol,
        addressing: CPU::zero_page_x,
        name: "ROL",
        addr_name: "ZPX",
        cycles: 6,
    },
    OpCode {
        execute: CPU::rla,
        addressing: CPU::zero_page_x,
        name: "RLA",
        addr_name: "ZPX",
        cycles: 6,
    },
    OpCode {
        execute: CPU::sec,
        addressing: CPU::implied,
        name: "SEC",
        addr_name: "IMP",
        cycles: 2,
    },
    OpCode {
        execute: CPU::and,
        addressing: CPU::absolute_y,
        name: "AND",
        addr_name: "ABY",
        cycles: 4,
    },
    OpCode {
        execute: CPU::nop,
        addressing: CPU::implied,
        name: "NOP",
        addr_name: "IMP",
        cycles: 2,
    },
    OpCode {
        execute: CPU::rla,
        addressing: CPU::absolute_y,
        name: "RLA",
        addr_name: "ABY",
        cycles: 7,
    },
    OpCode {
        execute: CPU::nop,
        addressing: CPU::absolute_x,
        name: "NOP",
        addr_name: "ABX",
        cycles: 4,
    },
    OpCode {
        execute: CPU::and,
        addressing: CPU::absolute_x,
        name: "AND",
        addr_name: "ABX",
        cycles: 4,
    },
    OpCode {
        execute: CPU::rol,
        addressing: CPU::absolute_x,
        name: "ROL",
        addr_name: "ABX",
        cycles: 7,
    },
    OpCode {
        execute: CPU::rla,
        addressing: CPU::absolute_x,
        name: "RLA",
        addr_name: "ABX",
        cycles: 7,
    },
    OpCode {
        execute: CPU::rti,
        addressing: CPU::implied,
        name: "RTI",
        addr_name: "IMP",
        cycles: 6,
    },
    OpCode {
        execute: CPU::eor,
        addressing: CPU::indirect_x,
        name: "EOR",
        addr_name: "IZX",
        cycles: 6,
    },
    OpCode {
        execute: CPU::eor,
        addressing: CPU::indirect_x,
        name: "EOR",
        addr_name: "IZX",
        cycles: 6,
    },
    OpCode {
        execute: CPU::sre,
        addressing: CPU::indirect_x,
        name: "SRE",
        addr_name: "IZX",
        cycles: 8,
    },
    OpCode {
        execute: CPU::nop,
        addressing: CPU::zero_page,
        name: "NOP",
        addr_name: "ZP",
        cycles: 3,
    },
    OpCode {
        execute: CPU::eor,
        addressing: CPU::zero_page,
        name: "EOR",
        addr_name: "ZP",
        cycles: 3,
    },
    OpCode {
        execute: CPU::lsr,
        addressing: CPU::zero_page,
        name: "LSR",
        addr_name: "ZP",
        cycles: 5,
    },
    OpCode {
        execute: CPU::sre,
        addressing: CPU::zero_page,
        name: "SRE",
        addr_name: "ZP",
        cycles: 5,
    },
    OpCode {
        execute: CPU::pha,
        addressing: CPU::implied,
        name: "PHA",
        addr_name: "IMP",
        cycles: 3,
    },
    OpCode {
        execute: CPU::eor,
        addressing: CPU::immediate,
        name: "EOR",
        addr_name: "IMM",
        cycles: 2,
    },
    OpCode {
        execute: CPU::lsr,
        addressing: CPU::implied,
        name: "LSR",
        addr_name: "IMP",
        cycles: 2,
    },
    OpCode {
        execute: CPU::alr,
        addressing: CPU::immediate,
        name: "ALR",
        addr_name: "IMM",
        cycles: 2,
    },
    OpCode {
        execute: CPU::jmp,
        addressing: CPU::absolute,
        name: "JMP",
        addr_name: "ABS",
        cycles: 3,
    },
    OpCode {
        execute: CPU::eor,
        addressing: CPU::absolute,
        name: "EOR",
        addr_name: "ABS",
        cycles: 4,
    },
    OpCode {
        execute: CPU::lsr,
        addressing: CPU::absolute,
        name: "LSR",
        addr_name: "ABS",
        cycles: 6,
    },
    OpCode {
        execute: CPU::sre,
        addressing: CPU::absolute,
        name: "SRE",
        addr_name: "ABS",
        cycles: 6,
    },
    OpCode {
        execute: CPU::bvc,
        addressing: CPU::relative,
        name: "BVC",
        addr_name: "REL",
        cycles: 2,
    },
    OpCode {
        execute: CPU::eor,
        addressing: CPU::indirect_y,
        name: "EOR",
        addr_name: "IZY",
        cycles: 5,
    },
    OpCode {
        execute: CPU::eor,
        addressing: CPU::indirect_y,
        name: "EOR",
        addr_name: "IZY",
        cycles: 5,
    },
    OpCode {
        execute: CPU::sre,
        addressing: CPU::indirect_y,
        name: "SRE",
        addr_name: "IZY",
        cycles: 8,
    },
    OpCode {
        execute: CPU::nop,
        addressing: CPU::zero_page_x,
        name: "NOP",
        addr_name: "ZPX",
        cycles: 4,
    },
    OpCode {
        execute: CPU::eor,
        addressing: CPU::zero_page_x,
        name: "EOR",
        addr_name: "ZPX",
        cycles: 4,
    },
    OpCode {
        execute: CPU::lsr,
        addressing: CPU::zero_page_x,
        name: "LSR",
        addr_name: "ZPX",
        cycles: 6,
    },
    OpCode {
        execute: CPU::sre,
        addressing: CPU::zero_page_x,
        name: "SRE",
        addr_name: "ZPX",
        cycles: 6,
    },
    OpCode {
        execute: CPU::cli,
        addressing: CPU::implied,
        name: "CLI",
        addr_name: "IMP",
        cycles: 2,
    },
    OpCode {
        execute: CPU::eor,
        addressing: CPU::absolute_y,
        name: "EOR",
        addr_name: "ABY",
        cycles: 4,
    },
    OpCode {
        execute: CPU::nop,
        addressing: CPU::implied,
        name: "NOP",
        addr_name: "IMP",
        cycles: 2,
    },
    OpCode {
        execute: CPU::sre,
        addressing: CPU::absolute_y,
        name: "SRE",
        addr_name: "ABY",
        cycles: 7,
    },
    OpCode {
        execute: CPU::nop,
        addressing: CPU::absolute_x,
        name: "NOP",
        addr_name: "ABX",
        cycles: 4,
    },
    OpCode {
        execute: CPU::eor,
        addressing: CPU::absolute_x,
        name: "EOR",
        addr_name: "ABX",
        cycles: 4,
    },
    OpCode {
        execute: CPU::lsr,
        addressing: CPU::absolute_x,
        name: "LSR",
        addr_name: "ABX",
        cycles: 7,
    },
    OpCode {
        execute: CPU::sre,
        addressing: CPU::absolute_x,
        name: "SRE",
        addr_name: "ABX",
        cycles: 7,
    },
    OpCode {
        execute: CPU::rts,
        addressing: CPU::implied,
        name: "RTS",
        addr_name: "IMP",
        cycles: 6,
    },
    OpCode {
        execute: CPU::adc,
        addressing: CPU::indirect_x,
        name: "ADC",
        addr_name: "IZX",
        cycles: 6,
    },
    OpCode {
        execute: CPU::adc,
        addressing: CPU::indirect_x,
        name: "ADC",
        addr_name: "IZX",
        cycles: 6,
    },
    OpCode {
        execute: CPU::rra,
        addressing: CPU::indirect_x,
        name: "RRA",
        addr_name: "IZX",
        cycles: 8,
    },
    OpCode {
        execute: CPU::nop,
        addressing: CPU::zero_page,
        name: "NOP",
        addr_name: "ZP",
        cycles: 3,
    },
    OpCode {
        execute: CPU::adc,
        addressing: CPU::zero_page,
        name: "ADC",
        addr_name: "ZP",
        cycles: 3,
    },
    OpCode {
        execute: CPU::ror,
        addressing: CPU::zero_page,
        name: "ROR",
        addr_name: "ZP",
        cycles: 5,
    },
    OpCode {
        execute: CPU::rra,
        addressing: CPU::zero_page,
        name: "RRA",
        addr_name: "ZP",
        cycles: 5,
    },
    OpCode {
        execute: CPU::pla,
        addressing: CPU::implied,
        name: "PLA",
        addr_name: "IMP",
        cycles: 4,
    },
    OpCode {
        execute: CPU::adc,
        addressing: CPU::immediate,
        name: "ADC",
        addr_name: "IMM",
        cycles: 2,
    },
    OpCode {
        execute: CPU::ror,
        addressing: CPU::implied,
        name: "ROR",
        addr_name: "IMP",
        cycles: 2,
    },
    OpCode {
        execute: CPU::arr,
        addressing: CPU::immediate,
        name: "ARR",
        addr_name: "IMM",
        cycles: 2,
    },
    OpCode {
        execute: CPU::jmp,
        addressing: CPU::indirect,
        name: "JMP",
        addr_name: "IND",
        cycles: 5,
    },
    OpCode {
        execute: CPU::adc,
        addressing: CPU::absolute,
        name: "ADC",
        addr_name: "ABS",
        cycles: 4,
    },
    OpCode {
        execute: CPU::ror,
        addressing: CPU::absolute,
        name: "ROR",
        addr_name: "ABS",
        cycles: 6,
    },
    OpCode {
        execute: CPU::rra,
        addressing: CPU::absolute,
        name: "RRA",
        addr_name: "ABS",
        cycles: 6,
    },
    OpCode {
        execute: CPU::bvs,
        addressing: CPU::relative,
        name: "BVS",
        addr_name: "REL",
        cycles: 2,
    },
    OpCode {
        execute: CPU::adc,
        addressing: CPU::indirect_y,
        name: "ADC",
        addr_name: "IZY",
        cycles: 5,
    },
    OpCode {
        execute: CPU::adc,
        addressing: CPU::indirect_y,
        name: "ADC",
        addr_name: "IZY",
        cycles: 5,
    },
    OpCode {
        execute: CPU::rra,
        addressing: CPU::indirect_y,
        name: "RRA",
        addr_name: "IZY",
        cycles: 8,
    },
    OpCode {
        execute: CPU::nop,
        addressing: CPU::zero_page_x,
        name: "NOP",
        addr_name: "ZPX",
        cycles: 4,
    },
    OpCode {
        execute: CPU::adc,
        addressing: CPU::zero_page_x,
        name: "ADC",
        addr_name: "ZPX",
        cycles: 4,
    },
    OpCode {
        execute: CPU::ror,
        addressing: CPU::zero_page_x,
        name: "ROR",
        addr_name: "ZPX",
        cycles: 6,
    },
    OpCode {
        execute: CPU::rra,
        addressing: CPU::zero_page_x,
        name: "RRA",
        addr_name: "ZPX",
        cycles: 6,
    },
    OpCode {
        execute: CPU::sei,
        addressing: CPU::implied,
        name: "SEI",
        addr_name: "IMP",
        cycles: 2,
    },
    OpCode {
        execute: CPU::adc,
        addressing: CPU::absolute_y,
        name: "ADC",
        addr_name: "ABY",
        cycles: 4,
    },
    OpCode {
        execute: CPU::nop,
        addressing: CPU::implied,
        name: "NOP",
        addr_name: "IMP",
        cycles: 2,
    },
    OpCode {
        execute: CPU::rra,
        addressing: CPU::absolute_y,
        name: "RRA",
        addr_name: "ABY",
        cycles: 7,
    },
    OpCode {
        execute: CPU::nop,
        addressing: CPU::absolute_x,
        name: "NOP",
        addr_name: "ABX",
        cycles: 4,
    },
    OpCode {
        execute: CPU::adc,
        addressing: CPU::absolute_x,
        name: "ADC",
        addr_name: "ABX",
        cycles: 4,
    },
    OpCode {
        execute: CPU::ror,
        addressing: CPU::absolute_x,
        name: "ROR",
        addr_name: "ABX",
        cycles: 7,
    },
    OpCode {
        execute: CPU::rra,
        addressing: CPU::absolute_x,
        name: "RRA",
        addr_name: "ABX",
        cycles: 7,
    },
    OpCode {
        execute: CPU::nop,
        addressing: CPU::immediate,
        name: "NOP",
        addr_name: "IMM",
        cycles: 2,
    },
    OpCode {
        execute: CPU::sta,
        addressing: CPU::indirect_x,
        name: "STA",
        addr_name: "IZX",
        cycles: 6,
    },
    OpCode {
        execute: CPU::nop,
        addressing: CPU::immediate,
        name: "NOP",
        addr_name: "IMM",
        cycles: 2,
    },
    OpCode {
        execute: CPU::sax,
        addressing: CPU::indirect_x,
        name: "SAX",
        addr_name: "IZX",
        cycles: 6,
    },
    OpCode {
        execute: CPU::sty,
        addressing: CPU::zero_page,
        name: "STY",
        addr_name: "ZP",
        cycles: 3,
    },
    OpCode {
        execute: CPU::sta,
        addressing: CPU::zero_page,
        name: "STA",
        addr_name: "ZP",
        cycles: 3,
    },
    OpCode {
        execute: CPU::stx,
        addressing: CPU::zero_page,
        name: "STX",
        addr_name: "ZP",
        cycles: 3,
    },
    OpCode {
        execute: CPU::sax,
        addressing: CPU::zero_page,
        name: "SAX",
        addr_name: "ZP",
        cycles: 3,
    },
    OpCode {
        execute: CPU::dey,
        addressing: CPU::implied,
        name: "DEY",
        addr_name: "IMP",
        cycles: 2,
    },
    OpCode {
        execute: CPU::nop,
        addressing: CPU::immediate,
        name: "NOP",
        addr_name: "IMM",
        cycles: 2,
    },
    OpCode {
        execute: CPU::txa,
        addressing: CPU::implied,
        name: "TXA",
        addr_name: "IMP",
        cycles: 2,
    },
    OpCode {
        execute: CPU::xaa,
        addressing: CPU::immediate,
        name: "XAA",
        addr_name: "IMM",
        cycles: 2,
    },
    OpCode {
        execute: CPU::sty,
        addressing: CPU::absolute,
        name: "STY",
        addr_name: "ABS",
        cycles: 4,
    },
    OpCode {
        execute: CPU::sta,
        addressing: CPU::absolute,
        name: "STA",
        addr_name: "ABS",
        cycles: 4,
    },
    OpCode {
        execute: CPU::stx,
        addressing: CPU::absolute,
        name: "STX",
        addr_name: "ABS",
        cycles: 4,
    },
    OpCode {
        execute: CPU::sax,
        addressing: CPU::absolute,
        name: "SAX",
        addr_name: "ABS",
        cycles: 4,
    },
    OpCode {
        execute: CPU::bcc,
        addressing: CPU::relative,
        name: "BCC",
        addr_name: "REL",
        cycles: 2,
    },
    OpCode {
        execute: CPU::sta,
        addressing: CPU::indirect_y,
        name: "STA",
        addr_name: "IZY",
        cycles: 6,
    },
    OpCode {
        execute: CPU::sta,
        addressing: CPU::indirect_y,
        name: "STA",
        addr_name: "IZY",
        cycles: 6,
    },
    OpCode {
        execute: CPU::ahx,
        addressing: CPU::indirect_y,
        name: "AHX",
        addr_name: "IZY",
        cycles: 6,
    },
    OpCode {
        execute: CPU::sty,
        addressing: CPU::zero_page_x,
        name: "STY",
        addr_name: "ZPX",
        cycles: 4,
    },
    OpCode {
        execute: CPU::sta,
        addressing: CPU::zero_page_x,
        name: "STA",
        addr_name: "ZPX",
        cycles: 4,
    },
    OpCode {
        execute: CPU::stx,
        addressing: CPU::zero_page_y,
        name: "STX",
        addr_name: "ZPY",
        cycles: 4,
    },
    OpCode {
        execute: CPU::sax,
        addressing: CPU::zero_page_y,
        name: "SAX",
        addr_name: "ZPY",
        cycles: 4,
    },
    OpCode {
        execute: CPU::tya,
        addressing: CPU::implied,
        name: "TYA",
        addr_name: "IMP",
        cycles: 2,
    },
    OpCode {
        execute: CPU::sta,
        addressing: CPU::absolute_y,
        name: "STA",
        addr_name: "ABY",
        cycles: 5,
    },
    OpCode {
        execute: CPU::txs,
        addressing: CPU::implied,
        name: "TXS",
        addr_name: "IMP",
        cycles: 2,
    },
    OpCode {
        execute: CPU::tas,
        addressing: CPU::absolute_y,
        name: "TAS",
        addr_name: "ABY",
        cycles: 5,
    },
    OpCode {
        execute: CPU::shy,
        addressing: CPU::absolute_x,
        name: "SHY",
        addr_name: "ABX",
        cycles: 5,
    },
    OpCode {
        execute: CPU::sta,
        addressing: CPU::absolute_x,
        name: "STA",
        addr_name: "ABX",
        cycles: 5,
    },
    OpCode {
        execute: CPU::shx,
        addressing: CPU::absolute_y,
        name: "SHX",
        addr_name: "ABY",
        cycles: 5,
    },
    OpCode {
        execute: CPU::ahx,
        addressing: CPU::absolute_y,
        name: "AHX",
        addr_name: "ABY",
        cycles: 5,
    },
    OpCode {
        execute: CPU::ldy,
        addressing: CPU::immediate,
        name: "LDY",
        addr_name: "IMM",
        cycles: 2,
    },
    OpCode {
        execute: CPU::lda,
        addressing: CPU::indirect_x,
        name: "LDA",
        addr_name: "IZX",
        cycles: 6,
    },
    OpCode {
        execute: CPU::ldx,
        addressing: CPU::immediate,
        name: "LDX",
        addr_name: "IMM",
        cycles: 2,
    },
    OpCode {
        execute: CPU::lax,
        addressing: CPU::indirect_x,
        name: "LAX",
        addr_name: "IZX",
        cycles: 6,
    },
    OpCode {
        execute: CPU::ldy,
        addressing: CPU::zero_page,
        name: "LDY",
        addr_name: "ZP",
        cycles: 3,
    },
    OpCode {
        execute: CPU::lda,
        addressing: CPU::zero_page,
        name: "LDA",
        addr_name: "ZP",
        cycles: 3,
    },
    OpCode {
        execute: CPU::ldx,
        addressing: CPU::zero_page,
        name: "LDX",
        addr_name: "ZP",
        cycles: 3,
    },
    OpCode {
        execute: CPU::lax,
        addressing: CPU::zero_page,
        name: "LAX",
        addr_name: "ZP",
        cycles: 3,
    },
    OpCode {
        execute: CPU::tay,
        addressing: CPU::implied,
        name: "TAY",
        addr_name: "IMP",
        cycles: 2,
    },
    OpCode {
        execute: CPU::lda,
        addressing: CPU::immediate,
        name: "LDA",
        addr_name: "IMM",
        cycles: 2,
    },
    OpCode {
        execute: CPU::tax,
        addressing: CPU::implied,
        name: "TAX",
        addr_name: "IMP",
        cycles: 2,
    },
    OpCode {
        execute: CPU::lax,
        addressing: CPU::immediate,
        name: "LAX",
        addr_name: "IMM",
        cycles: 2,
    },
    OpCode {
        execute: CPU::ldy,
        addressing: CPU::absolute,
        name: "LDY",
        addr_name: "ABS",
        cycles: 4,
    },
    OpCode {
        execute: CPU::lda,
        addressing: CPU::absolute,
        name: "LDA",
        addr_name: "ABS",
        cycles: 4,
    },
    OpCode {
        execute: CPU::ldx,
        addressing: CPU::absolute,
        name: "LDX",
        addr_name: "ABS",
        cycles: 4,
    },
    OpCode {
        execute: CPU::lax,
        addressing: CPU::absolute,
        name: "LAX",
        addr_name: "ABS",
        cycles: 4,
    },
    OpCode {
        execute: CPU::bcs,
        addressing: CPU::relative,
        name: "BCS",
        addr_name: "REL",
        cycles: 2,
    },
    OpCode {
        execute: CPU::lda,
        addressing: CPU::indirect_y,
        name: "LDA",
        addr_name: "IZY",
        cycles: 5,
    },
    OpCode {
        execute: CPU::lda,
        addressing: CPU::indirect_y,
        name: "LDA",
        addr_name: "IZY",
        cycles: 5,
    },
    OpCode {
        execute: CPU::lax,
        addressing: CPU::indirect_y,
        name: "LAX",
        addr_name: "IZY",
        cycles: 5,
    },
    OpCode {
        execute: CPU::ldy,
        addressing: CPU::zero_page_x,
        name: "LDY",
        addr_name: "ZPX",
        cycles: 4,
    },
    OpCode {
        execute: CPU::lda,
        addressing: CPU::zero_page_x,
        name: "LDA",
        addr_name: "ZPX",
        cycles: 4,
    },
    OpCode {
        execute: CPU::ldx,
        addressing: CPU::zero_page_y,
        name: "LDX",
        addr_name: "ZPY",
        cycles: 4,
    },
    OpCode {
        execute: CPU::lax,
        addressing: CPU::zero_page_y,
        name: "LAX",
        addr_name: "ZPY",
        cycles: 4,
    },
    OpCode {
        execute: CPU::clv,
        addressing: CPU::implied,
        name: "CLV",
        addr_name: "IMP",
        cycles: 2,
    },
    OpCode {
        execute: CPU::lda,
        addressing: CPU::absolute_y,
        name: "LDA",
        addr_name: "ABY",
        cycles: 4,
    },
    OpCode {
        execute: CPU::tsx,
        addressing: CPU::implied,
        name: "TSX",
        addr_name: "IMP",
        cycles: 2,
    },
    OpCode {
        execute: CPU::las,
        addressing: CPU::absolute_y,
        name: "LAS",
        addr_name: "ABY",
        cycles: 4,
    },
    OpCode {
        execute: CPU::ldy,
        addressing: CPU::absolute_x,
        name: "LDY",
        addr_name: "ABX",
        cycles: 4,
    },
    OpCode {
        execute: CPU::lda,
        addressing: CPU::absolute_x,
        name: "LDA",
        addr_name: "ABX",
        cycles: 4,
    },
    OpCode {
        execute: CPU::ldx,
        addressing: CPU::absolute_y,
        name: "LDX",
        addr_name: "ABY",
        cycles: 4,
    },
    OpCode {
        execute: CPU::lax,
        addressing: CPU::absolute_y,
        name: "LAX",
        addr_name: "ABY",
        cycles: 4,
    },
    OpCode {
        execute: CPU::cpy,
        addressing: CPU::immediate,
        name: "CPY",
        addr_name: "IMM",
        cycles: 2,
    },
    OpCode {
        execute: CPU::cmp,
        addressing: CPU::indirect_x,
        name: "CMP",
        addr_name: "IZX",
        cycles: 6,
    },
    OpCode {
        execute: CPU::nop,
        addressing: CPU::immediate,
        name: "NOP",
        addr_name: "IMM",
        cycles: 2,
    },
    OpCode {
        execute: CPU::dcp,
        addressing: CPU::indirect_x,
        name: "DCP",
        addr_name: "IZX",
        cycles: 8,
    },
    OpCode {
        execute: CPU::cpy,
        addressing: CPU::zero_page,
        name: "CPY",
        addr_name: "ZP",
        cycles: 3,
    },
    OpCode {
        execute: CPU::cmp,
        addressing: CPU::zero_page,
        name: "CMP",
        addr_name: "ZP",
        cycles: 3,
    },
    OpCode {
        execute: CPU::dec,
        addressing: CPU::zero_page,
        name: "DEC",
        addr_name: "ZP",
        cycles: 5,
    },
    OpCode {
        execute: CPU::dcp,
        addressing: CPU::zero_page,
        name: "DCP",
        addr_name: "ZP",
        cycles: 5,
    },
    OpCode {
        execute: CPU::iny,
        addressing: CPU::implied,
        name: "INY",
        addr_name: "IMP",
        cycles: 2,
    },
    OpCode {
        execute: CPU::cmp,
        addressing: CPU::immediate,
        name: "CMP",
        addr_name: "IMM",
        cycles: 2,
    },
    OpCode {
        execute: CPU::dex,
        addressing: CPU::implied,
        name: "DEX",
        addr_name: "IMP",
        cycles: 2,
    },
    OpCode {
        execute: CPU::axs,
        addressing: CPU::immediate,
        name: "AXS",
        addr_name: "IMM",
        cycles: 2,
    },
    OpCode {
        execute: CPU::cpy,
        addressing: CPU::absolute,
        name: "CPY",
        addr_name: "ABS",
        cycles: 4,
    },
    OpCode {
        execute: CPU::cmp,
        addressing: CPU::absolute,
        name: "CMP",
        addr_name: "ABS",
        cycles: 4,
    },
    OpCode {
        execute: CPU::dec,
        addressing: CPU::absolute,
        name: "DEC",
        addr_name: "ABS",
        cycles: 6,
    },
    OpCode {
        execute: CPU::dcp,
        addressing: CPU::absolute,
        name: "DCP",
        addr_name: "ABS",
        cycles: 6,
    },
    OpCode {
        execute: CPU::bne,
        addressing: CPU::relative,
        name: "BNE",
        addr_name: "REL",
        cycles: 2,
    },
    OpCode {
        execute: CPU::cmp,
        addressing: CPU::indirect_y,
        name: "CMP",
        addr_name: "IZY",
        cycles: 5,
    },
    OpCode {
        execute: CPU::cmp,
        addressing: CPU::indirect_y,
        name: "CMP",
        addr_name: "IZY",
        cycles: 5,
    },
    OpCode {
        execute: CPU::dcp,
        addressing: CPU::indirect_y,
        name: "DCP",
        addr_name: "IZY",
        cycles: 8,
    },
    OpCode {
        execute: CPU::nop,
        addressing: CPU::zero_page_x,
        name: "NOP",
        addr_name: "ZPX",
        cycles: 4,
    },
    OpCode {
        execute: CPU::cmp,
        addressing: CPU::zero_page_x,
        name: "CMP",
        addr_name: "ZPX",
        cycles: 4,
    },
    OpCode {
        execute: CPU::dec,
        addressing: CPU::zero_page_x,
        name: "DEC",
        addr_name: "ZPX",
        cycles: 6,
    },
    OpCode {
        execute: CPU::dcp,
        addressing: CPU::zero_page_x,
        name: "DCP",
        addr_name: "ZPX",
        cycles: 6,
    },
    OpCode {
        execute: CPU::cld,
        addressing: CPU::implied,
        name: "CLD",
        addr_name: "IMP",
        cycles: 2,
    },
    OpCode {
        execute: CPU::cmp,
        addressing: CPU::absolute_y,
        name: "CMP",
        addr_name: "ABY",
        cycles: 4,
    },
    OpCode {
        execute: CPU::nop,
        addressing: CPU::implied,
        name: "NOP",
        addr_name: "IMP",
        cycles: 2,
    },
    OpCode {
        execute: CPU::dcp,
        addressing: CPU::absolute_y,
        name: "DCP",
        addr_name: "ABY",
        cycles: 7,
    },
    OpCode {
        execute: CPU::nop,
        addressing: CPU::absolute_x,
        name: "NOP",
        addr_name: "ABX",
        cycles: 4,
    },
    OpCode {
        execute: CPU::cmp,
        addressing: CPU::absolute_x,
        name: "CMP",
        addr_name: "ABX",
        cycles: 4,
    },
    OpCode {
        execute: CPU::dec,
        addressing: CPU::absolute_x,
        name: "DEC",
        addr_name: "ABX",
        cycles: 7,
    },
    OpCode {
        execute: CPU::dcp,
        addressing: CPU::absolute_x,
        name: "DCP",
        addr_name: "ABX",
        cycles: 7,
    },
    OpCode {
        execute: CPU::cpx,
        addressing: CPU::immediate,
        name: "CPX",
        addr_name: "IMM",
        cycles: 2,
    },
    OpCode {
        execute: CPU::sbc,
        addressing: CPU::indirect_x,
        name: "SBC",
        addr_name: "IZX",
        cycles: 6,
    },
    OpCode {
        execute: CPU::nop,
        addressing: CPU::immediate,
        name: "NOP",
        addr_name: "IMM",
        cycles: 2,
    },
    OpCode {
        execute: CPU::isc,
        addressing: CPU::indirect_x,
        name: "ISC",
        addr_name: "IZX",
        cycles: 8,
    },
    OpCode {
        execute: CPU::cpx,
        addressing: CPU::zero_page,
        name: "CPX",
        addr_name: "ZP",
        cycles: 3,
    },
    OpCode {
        execute: CPU::sbc,
        addressing: CPU::zero_page,
        name: "SBC",
        addr_name: "ZP",
        cycles: 3,
    },
    OpCode {
        execute: CPU::inc,
        addressing: CPU::zero_page,
        name: "INC",
        addr_name: "ZP",
        cycles: 5,
    },
    OpCode {
        execute: CPU::isc,
        addressing: CPU::zero_page,
        name: "ISC",
        addr_name: "ZP",
        cycles: 5,
    },
    OpCode {
        execute: CPU::inx,
        addressing: CPU::implied,
        name: "INX",
        addr_name: "IMP",
        cycles: 2,
    },
    OpCode {
        execute: CPU::sbc,
        addressing: CPU::immediate,
        name: "SBC",
        addr_name: "IMM",
        cycles: 2,
    },
    OpCode {
        execute: CPU::nop,
        addressing: CPU::implied,
        name: "NOP",
        addr_name: "IMP",
        cycles: 2,
    },
    OpCode {
        execute: CPU::sbc,
        addressing: CPU::immediate,
        name: "SBC",
        addr_name: "IMM",
        cycles: 2,
    },
    OpCode {
        execute: CPU::cpx,
        addressing: CPU::absolute,
        name: "CPX",
        addr_name: "ABS",
        cycles: 4,
    },
    OpCode {
        execute: CPU::sbc,
        addressing: CPU::absolute,
        name: "SBC",
        addr_name: "ABS",
        cycles: 4,
    },
    OpCode {
        execute: CPU::inc,
        addressing: CPU::absolute,
        name: "INC",
        addr_name: "ABS",
        cycles: 6,
    },
    OpCode {
        execute: CPU::isc,
        addressing: CPU::absolute,
        name: "ISC",
        addr_name: "ABS",
        cycles: 6,
    },
    OpCode {
        execute: CPU::beq,
        addressing: CPU::relative,
        name: "BEQ",
        addr_name: "REL",
        cycles: 2,
    },
    OpCode {
        execute: CPU::sbc,
        addressing: CPU::indirect_y,
        name: "SBC",
        addr_name: "IZY",
        cycles: 5,
    },
    OpCode {
        execute: CPU::sbc,
        addressing: CPU::indirect_y,
        name: "SBC",
        addr_name: "IZY",
        cycles: 5,
    },
    OpCode {
        execute: CPU::isc,
        addressing: CPU::indirect_y,
        name: "ISC",
        addr_name: "IZY",
        cycles: 8,
    },
    OpCode {
        execute: CPU::nop,
        addressing: CPU::zero_page_x,
        name: "NOP",
        addr_name: "ZPX",
        cycles: 4,
    },
    OpCode {
        execute: CPU::sbc,
        addressing: CPU::zero_page_x,
        name: "SBC",
        addr_name: "ZPX",
        cycles: 4,
    },
    OpCode {
        execute: CPU::inc,
        addressing: CPU::zero_page_x,
        name: "INC",
        addr_name: "ZPX",
        cycles: 6,
    },
    OpCode {
        execute: CPU::isc,
        addressing: CPU::zero_page_x,
        name: "ISC",
        addr_name: "ZPX",
        cycles: 6,
    },
    OpCode {
        execute: CPU::sed,
        addressing: CPU::implied,
        name: "SED",
        addr_name: "IMP",
        cycles: 2,
    },
    OpCode {
        execute: CPU::sbc,
        addressing: CPU::absolute_y,
        name: "SBC",
        addr_name: "ABY",
        cycles: 4,
    },
    OpCode {
        execute: CPU::nop,
        addressing: CPU::implied,
        name: "NOP",
        addr_name: "IMP",
        cycles: 2,
    },
    OpCode {
        execute: CPU::isc,
        addressing: CPU::absolute_y,
        name: "ISC",
        addr_name: "ABY",
        cycles: 7,
    },
    OpCode {
        execute: CPU::nop,
        addressing: CPU::absolute_x,
        name: "NOP",
        addr_name: "ABX",
        cycles: 4,
    },
    OpCode {
        execute: CPU::sbc,
        addressing: CPU::absolute_x,
        name: "SBC",
        addr_name: "ABX",
        cycles: 4,
    },
    OpCode {
        execute: CPU::inc,
        addressing: CPU::absolute_x,
        name: "INC",
        addr_name: "ABX",
        cycles: 7,
    },
    OpCode {
        execute: CPU::isc,
        addressing: CPU::absolute_x,
        name: "ISC",
        addr_name: "ABX",
        cycles: 7,
    },
];

impl CPU {
    fn txs(&mut self, _address: Address) {
        todo!("txs Not Implemented")
    }

    fn rti(&mut self, _address: Address) {
        todo!("rti Not Implemented")
    }

    fn tya(&mut self, _address: Address) {
        todo!("tya Not Implemented")
    }

    fn dex(&mut self, _address: Address) {
        todo!("dex Not Implemented")
    }

    fn asl(&mut self, _address: Address) {
        todo!("asl Not Implemented")
    }

    fn rol(&mut self, _address: Address) {
        todo!("rol Not Implemented")
    }

    fn lsr(&mut self, _address: Address) {
        todo!("lsr Not Implemented")
    }

    fn rts(&mut self, _address: Address) {
        todo!("rts Not Implemented")
    }

    fn sbc(&mut self, _address: Address) {
        todo!("sbc Not Implemented")
    }

    fn shy(&mut self, _address: Address) {
        todo!("shy Not Implemented")
    }

    fn dec(&mut self, _address: Address) {
        todo!("dec Not Implemented")
    }

    fn clc(&mut self, _address: Address) {
        todo!("clc Not Implemented")
    }

    fn brk(&mut self, _address: Address) {
        todo!("brk Not Implemented")
    }

    fn sre(&mut self, _address: Address) {
        todo!("sre Not Implemented")
    }

    fn eor(&mut self, _address: Address) {
        todo!("eor Not Implemented")
    }

    fn pla(&mut self, _address: Address) {
        todo!("pla Not Implemented")
    }

    fn sec(&mut self, _address: Address) {
        todo!("sec Not Implemented")
    }

    fn anc(&mut self, _address: Address) {
        todo!("anc Not Implemented")
    }

    fn cld(&mut self, _address: Address) {
        todo!("cld Not Implemented")
    }

    fn rla(&mut self, _address: Address) {
        todo!("rla Not Implemented")
    }

    fn inx(&mut self, _address: Address) {
        todo!("inx Not Implemented")
    }

    fn and(&mut self, _address: Address) {
        todo!("and Not Implemented")
    }

    fn tas(&mut self, _address: Address) {
        todo!("tas Not Implemented")
    }

    fn alr(&mut self, _address: Address) {
        todo!("alr Not Implemented")
    }

    fn pha(&mut self, _address: Address) {
        todo!("pha Not Implemented")
    }

    fn ror(&mut self, _address: Address) {
        todo!("ror Not Implemented")
    }

    fn txa(&mut self, _address: Address) {
        todo!("txa Not Implemented")
    }

    fn php(&mut self, _address: Address) {
        todo!("php Not Implemented")
    }

    fn shx(&mut self, _address: Address) {
        todo!("shx Not Implemented")
    }

    fn bne(&mut self, _address: Address) {
        todo!("bne Not Implemented")
    }

    fn beq(&mut self, _address: Address) {
        todo!("beq Not Implemented")
    }

    fn ahx(&mut self, _address: Address) {
        todo!("ahx Not Implemented")
    }

    fn cli(&mut self, _address: Address) {
        todo!("cli Not Implemented")
    }

    fn bvc(&mut self, _address: Address) {
        todo!("bvc Not Implemented")
    }

    fn bcc(&mut self, _address: Address) {
        todo!("bcc Not Implemented")
    }

    fn bcs(&mut self, _address: Address) {
        todo!("bcs Not Implemented")
    }

    fn bpl(&mut self, _address: Address) {
        todo!("bpl Not Implemented")
    }

    fn axs(&mut self, _address: Address) {
        todo!("axs Not Implemented")
    }

    fn sed(&mut self, _address: Address) {
        todo!("sed Not Implemented")
    }

    fn arr(&mut self, _address: Address) {
        todo!("arr Not Implemented")
    }

    fn tsx(&mut self, _address: Address) {
        todo!("tsx Not Implemented")
    }

    fn jsr(&mut self, _address: Address) {
        todo!("jsr Not Implemented")
    }

    fn plp(&mut self, _address: Address) {
        todo!("plp Not Implemented")
    }

    fn cpy(&mut self, _address: Address) {
        todo!("cpy Not Implemented")
    }

    fn dcp(&mut self, _address: Address) {
        todo!("dcp Not Implemented")
    }

    fn ora(&mut self, _address: Address) {
        todo!("ora Not Implemented")
    }

    fn tax(&mut self, _address: Address) {
        todo!("tax Not Implemented")
    }

    fn clv(&mut self, _address: Address) {
        todo!("clv Not Implemented")
    }

    fn rra(&mut self, _address: Address) {
        todo!("rra Not Implemented")
    }

    fn nop(&mut self, _address: Address) {
        todo!("nop Not Implemented")
    }

    fn slo(&mut self, _address: Address) {
        todo!("slo Not Implemented")
    }

    fn bmi(&mut self, _address: Address) {
        todo!("bmi Not Implemented")
    }

    fn xaa(&mut self, _address: Address) {
        todo!("xaa Not Implemented")
    }

    fn bit(&mut self, _address: Address) {
        todo!("bit Not Implemented")
    }

    fn tay(&mut self, _address: Address) {
        todo!("tay Not Implemented")
    }

    fn sax(&mut self, _address: Address) {
        todo!("sax Not Implemented")
    }

    fn cmp(&mut self, _address: Address) {
        todo!("cmp Not Implemented")
    }

    fn cpx(&mut self, _address: Address) {
        todo!("cpx Not Implemented")
    }

    fn las(&mut self, _address: Address) {
        todo!("las Not Implemented")
    }

    fn isc(&mut self, _address: Address) {
        todo!("isc Not Implemented")
    }

    fn lax(&mut self, _address: Address) {
        todo!("lax Not Implemented")
    }

    fn dey(&mut self, _address: Address) {
        todo!("dey Not Implemented")
    }

    fn bvs(&mut self, _address: Address) {
        todo!("bvs Not Implemented")
    }

    fn sei(&mut self, _address: Address) {
        todo!("sei Not Implemented")
    }
}

bitflags! {
    struct StatusFlags: u8 {
        const C = 1;
        const Z = 1 << 1;
        const I = 1 << 2;
        const D = 1 << 3;
        const B = 1 << 4;
        const X = 1 << 5;
        const O = 1 << 6;
        const N = 1 << 7;
    }
}

pub struct CPU {
    accumulator: u8,
    x_register: u8,
    y_register: u8,
    program_counter: u16,
    remaining_cycles: u8,
    bus: Box<dyn Bus>,
    status: StatusFlags,
}

impl CPU {
    pub fn new(pc: u16, bus: Box<dyn Bus>) -> Self {
        Self {
            accumulator: 0x00,
            x_register: 0x00,
            y_register: 0x00,
            program_counter: pc,
            remaining_cycles: 0,
            bus,
            status: StatusFlags::empty(),
        }
    }

    fn cycle(&mut self) {
        if self.remaining_cycles == 0 {
            // TODO: log instead of print
            let opcode = self.bus.read(self.program_counter);
            let current_pc = self.program_counter; // for logging

            self.program_counter += 1;

            let op = OPCODE_TABLE[opcode as usize];

            let address = (op.addressing)(self);

            (op.execute)(self, address);

            println!(
                "{:#04x} {} {} {}",
                current_pc, op.name, op.addr_name, address
            );

            self.remaining_cycles += op.cycles;
        }
        self.remaining_cycles -= 1;
    }

    pub fn step(&mut self) {
        self.cycle();
        while self.remaining_cycles != 0 {
            self.cycle();
        }
    }
}

// Operations
impl CPU {
    fn lda(&mut self, address: Address) {
        match address {
            Address::Absolute(address) => {
                self.accumulator = self.bus.read(address);
                if self.accumulator == 0 {
                    self.status |= StatusFlags::Z;
                }
                if self.accumulator & StatusFlags::N.bits() != 0 {
                    self.status |= StatusFlags::N;
                }
            }
            _ => panic!("LDA called with invalid addressing mode"),
        }
    }

    fn sta(&mut self, address: Address) {
        match address {
            Address::Absolute(address) => {
                self.bus.write(address, self.accumulator);
            }
            _ => panic!("STA called with invalid addressing mode"),
        }
    }

    fn adc(&mut self, address: Address) {
        match address {
            Address::Absolute(address) => {
                let value = self.bus.read(address);
                let result: u16 = u16::from(self.accumulator) + u16::from(value);
                self.accumulator = result as u8;
                // TODO: flags
            }
            _ => panic!("ADC called with invalid addressing mode"),
        }
    }

    fn inc(&mut self, address: Address) {
        match address {
            Address::Absolute(address) => {
                let value = self.bus.read(address).wrapping_add(1);
                self.bus.write(address, value);
            }
            _ => panic!("INC called with invalid addressing mode"),
        }
    }

    fn iny(&mut self, address: Address) {
        match address {
            Address::Implied => {
                self.y_register = self.y_register.wrapping_add(1);
                // TODO: flags
            }
            _ => panic!("INY called with invalid addressing mode"),
        }
    }

    fn ldx(&mut self, address: Address) {
        match address {
            Address::Absolute(address) => {
                self.x_register = self.bus.read(address);
                // TODO: flags
            }
            _ => panic!("LDX called with invalid addressing mode"),
        }
    }

    fn ldy(&mut self, address: Address) {
        match address {
            Address::Absolute(address) => {
                self.y_register = self.bus.read(address);
                // TODO: flags
            }
            _ => panic!("LDY called with invalid addressing mode"),
        }
    }

    fn jmp(&mut self, address: Address) {
        match address {
            Address::Absolute(address) => {
                self.program_counter = address;
            }
            _ => panic!("LDY called with invalid addressing mode"),
        }
    }

    fn stx(&mut self, address: Address) {
        match address {
            Address::Absolute(address) => self.bus.write(address, self.x_register),
            _ => panic!("STX called with invalid addressing mode"),
        }
    }

    fn sty(&mut self, address: Address) {
        match address {
            Address::Absolute(address) => self.bus.write(address, self.y_register),
            _ => panic!("STY called with invalid addressing mode"),
        }
    }
}

// Addressing modes
impl CPU {
    fn implied(&mut self) -> Address {
        Address::Implied
    }

    fn immediate(&mut self) -> Address {
        let address = self.program_counter;
        self.program_counter += 1;

        Address::Absolute(address)
    }

    fn zero_page(&mut self) -> Address {
        let address = u16::from(self.bus.read(self.program_counter));
        self.program_counter += 1;
        Address::Absolute(address)
    }

    fn zero_page_x(&mut self) -> Address {
        todo!()
    }

    fn zero_page_y(&mut self) -> Address {
        todo!()
    }

    fn absolute(&mut self) -> Address {
        let address = self.bus.read16(self.program_counter);
        self.program_counter += 2;
        Address::Absolute(address)
    }

    fn absolute_x(&mut self) -> Address {
        todo!("absolute_x")
    }

    fn absolute_y(&mut self) -> Address {
        todo!("absolute_y")
    }

    fn indirect(&mut self) -> Address {
        todo!("indirect")
    }

    fn indirect_x(&mut self) -> Address {
        todo!("indirect_x")
    }

    fn indirect_y(&mut self) -> Address {
        todo!("indirect_y")
    }

    fn relative(&mut self) -> Address {
        todo!("relative")
    }
}

#[cfg(test)]
mod tests {
    use super::{Bus, CPU};

    impl Bus for Vec<u8> {
        fn read(&self, address: u16) -> u8 {
            self[address as usize]
        }

        fn write(&mut self, address: u16, value: u8) {
            self[address as usize] = value;
        }
    }

    #[test]
    fn test_simple_program() {
        let program = [
            0xa9, 0x10, // LDA #$10     -> A = #$10
            0x85, 0x20, // STA $20      -> $20 = #$10
            0xa9, 0x01, // LDA #$1      -> A = #$1
            0x65, 0x20, // ADC $20      -> A = #$11
            0x85, 0x21, // STA $21      -> $21=#$11
            0xe6, 0x21, // INC $21      -> $21=#$12
            0xa4, 0x21, // LDY $21      -> Y=#$12
            0xc8, // INY          -> Y=#$13
            0x00, // BRK
        ];

        let mut ram = [0u8; 65536];
        ram[0x0000..program.len()].copy_from_slice(&program);

        let mut cpu = CPU::new(0x00, Box::new(ram));

        // LDA #$10
        cpu.step();

        assert_eq!(cpu.accumulator, 0x10);

        // STA $20
        cpu.step();

        assert_eq!(cpu.bus.read(0x20), 0x10);

        // LDA #$1
        cpu.step();
        assert_eq!(cpu.accumulator, 0x01);

        // ADC $20
        cpu.step();
        assert_eq!(cpu.accumulator, 0x11);

        // STA $21
        cpu.step();
        assert_eq!(cpu.bus.read(0x21), 0x11);

        // INC $21
        cpu.step();
        assert_eq!(cpu.bus.read(0x21), 0x12);

        // LDY $21
        cpu.step();
        assert_eq!(cpu.y_register, 0x12);

        // INY
        cpu.step();
        assert_eq!(cpu.y_register, 0x13);
    }

    #[test]
    fn test_euclid_algo() {
        let program = [
            // (F)irst | (S)econd
            // .algo
            0xa5, 0x00, // Load from F to A
            // .algo_
            0x38, // Set carry flag
            0xe5, 0x01, // Substract S from number in A (from F)
            0xf0, 0x07, // Jump to .end if diff is zero
            0x30, 0x08, // Jump to .swap if diff is negative
            0x85, 0x00, // Load A to F
            0x4c, 0x12, 0x00, // Jump to .algo_
            // .end
            0xa5, 0x00, // Load from S to A
            0xff, // .swap
            0xa6, 0x00, // load F to X
            0xa4, 0x01, // load S to Y
            0x86, 0x01, // Store X to F
            0x84, 0x00, // Store Y to S
            0x4c, 0x10, 0x00, // Jump to .algo
        ];

        let mut ram = [0u8; 65536];
        ram[0x00] = 56;
        ram[0x01] = 49;
        ram[0xC000..program.len()].copy_from_slice(&program);

        let mut cpu = CPU::new(0xC000, Box::new(ram));
    }
}
