use crate::cpu::CPU;

#[derive(Debug, Clone, Copy)]
pub(crate) enum Address {
    Implied,
    Absolute(u16, bool), // address, is_page_cross
    Relative(u8),
}

#[derive(Debug, Copy, Clone)]
pub(crate) enum AddressingMode {
    Absolute,
    AbsoluteX,
    AbsoluteY,
    Implied,
    Immediate,
    ZeroPage,
    ZeroPageX,
    ZeroPageY,
    Relative,
    IndirectX,
    IndirectY,
    Indirect,
}

#[derive(Debug, Copy, Clone)]
pub(crate) struct OpCode {
    execute: fn(&mut CPU, Address),
    name: &'static str,
    addressing: AddressingMode,
    cycles: u8,
}

impl OpCode {
    pub fn len(&self) -> u16 {
        match self.addressing {
            AddressingMode::Absolute
            | AddressingMode::AbsoluteY
            | AddressingMode::AbsoluteX
            | AddressingMode::Indirect => 3,

            AddressingMode::Immediate
            | AddressingMode::ZeroPage
            | AddressingMode::ZeroPageX
            | AddressingMode::Relative
            | AddressingMode::IndirectX
            | AddressingMode::IndirectY
            | AddressingMode::ZeroPageY => 2,

            AddressingMode::Implied => 1,
        }
    }

    pub fn name(&self) -> &'static str {
        self.name
    }

    pub fn addressing(&self) -> AddressingMode {
        self.addressing
    }

    pub fn cycles(&self) -> u8 {
        self.cycles
    }

    pub fn execute(&self, cpu: &mut CPU, address: Address) {
        (self.execute)(cpu, address)
    }
}

// Autogenerated from opcode_table_generator.py
pub(crate) static OPCODE_TABLE: [OpCode; 256] = [
    // Opcode: 0x00
    OpCode {
        execute: CPU::brk,
        name: "BRK",
        addressing: AddressingMode::Implied,
        cycles: 7,
    },
    // Opcode: 0x01
    OpCode {
        execute: CPU::ora,
        name: "ORA",
        addressing: AddressingMode::IndirectX,
        cycles: 6,
    },
    // Opcode: 0x01
    OpCode {
        execute: CPU::ora,
        name: "ORA",
        addressing: AddressingMode::IndirectX,
        cycles: 6,
    },
    // Opcode: 0x03
    OpCode {
        execute: CPU::slo,
        name: "SLO",
        addressing: AddressingMode::IndirectX,
        cycles: 8,
    },
    // Opcode: 0x04
    OpCode {
        execute: CPU::nop,
        name: "NOP",
        addressing: AddressingMode::ZeroPage,
        cycles: 3,
    },
    // Opcode: 0x05
    OpCode {
        execute: CPU::ora,
        name: "ORA",
        addressing: AddressingMode::ZeroPage,
        cycles: 3,
    },
    // Opcode: 0x06
    OpCode {
        execute: CPU::asl,
        name: "ASL",
        addressing: AddressingMode::ZeroPage,
        cycles: 5,
    },
    // Opcode: 0x07
    OpCode {
        execute: CPU::slo,
        name: "SLO",
        addressing: AddressingMode::ZeroPage,
        cycles: 5,
    },
    // Opcode: 0x08
    OpCode {
        execute: CPU::php,
        name: "PHP",
        addressing: AddressingMode::Implied,
        cycles: 3,
    },
    // Opcode: 0x09
    OpCode {
        execute: CPU::ora,
        name: "ORA",
        addressing: AddressingMode::Immediate,
        cycles: 2,
    },
    // Opcode: 0x0A
    OpCode {
        execute: CPU::asl,
        name: "ASL",
        addressing: AddressingMode::Implied,
        cycles: 2,
    },
    // Opcode: 0x0B
    OpCode {
        execute: CPU::anc,
        name: "ANC",
        addressing: AddressingMode::Immediate,
        cycles: 2,
    },
    // Opcode: 0x0C
    OpCode {
        execute: CPU::nop,
        name: "NOP",
        addressing: AddressingMode::Absolute,
        cycles: 4,
    },
    // Opcode: 0x0D
    OpCode {
        execute: CPU::ora,
        name: "ORA",
        addressing: AddressingMode::Absolute,
        cycles: 4,
    },
    // Opcode: 0x0E
    OpCode {
        execute: CPU::asl,
        name: "ASL",
        addressing: AddressingMode::Absolute,
        cycles: 6,
    },
    // Opcode: 0x0F
    OpCode {
        execute: CPU::slo,
        name: "SLO",
        addressing: AddressingMode::Absolute,
        cycles: 6,
    },
    // Opcode: 0x10
    OpCode {
        execute: CPU::bpl,
        name: "BPL",
        addressing: AddressingMode::Relative,
        cycles: 2,
    },
    // Opcode: 0x11
    OpCode {
        execute: CPU::ora,
        name: "ORA",
        addressing: AddressingMode::IndirectY,
        cycles: 5,
    },
    // Opcode: 0x11
    OpCode {
        execute: CPU::ora,
        name: "ORA",
        addressing: AddressingMode::IndirectY,
        cycles: 5,
    },
    // Opcode: 0x13
    OpCode {
        execute: CPU::slo,
        name: "SLO",
        addressing: AddressingMode::IndirectY,
        cycles: 8,
    },
    // Opcode: 0x14
    OpCode {
        execute: CPU::nop,
        name: "NOP",
        addressing: AddressingMode::ZeroPageX,
        cycles: 4,
    },
    // Opcode: 0x15
    OpCode {
        execute: CPU::ora,
        name: "ORA",
        addressing: AddressingMode::ZeroPageX,
        cycles: 4,
    },
    // Opcode: 0x16
    OpCode {
        execute: CPU::asl,
        name: "ASL",
        addressing: AddressingMode::ZeroPageX,
        cycles: 6,
    },
    // Opcode: 0x17
    OpCode {
        execute: CPU::slo,
        name: "SLO",
        addressing: AddressingMode::ZeroPageX,
        cycles: 6,
    },
    // Opcode: 0x18
    OpCode {
        execute: CPU::clc,
        name: "CLC",
        addressing: AddressingMode::Implied,
        cycles: 2,
    },
    // Opcode: 0x19
    OpCode {
        execute: CPU::ora,
        name: "ORA",
        addressing: AddressingMode::AbsoluteY,
        cycles: 4,
    },
    // Opcode: 0x1A
    OpCode {
        execute: CPU::nop,
        name: "NOP",
        addressing: AddressingMode::Implied,
        cycles: 2,
    },
    // Opcode: 0x1B
    OpCode {
        execute: CPU::slo,
        name: "SLO",
        addressing: AddressingMode::AbsoluteY,
        cycles: 7,
    },
    // Opcode: 0x1C
    OpCode {
        execute: CPU::nop,
        name: "NOP",
        addressing: AddressingMode::AbsoluteX,
        cycles: 4,
    },
    // Opcode: 0x1D
    OpCode {
        execute: CPU::ora,
        name: "ORA",
        addressing: AddressingMode::AbsoluteX,
        cycles: 4,
    },
    // Opcode: 0x1E
    OpCode {
        execute: CPU::asl,
        name: "ASL",
        addressing: AddressingMode::AbsoluteX,
        cycles: 7,
    },
    // Opcode: 0x1F
    OpCode {
        execute: CPU::slo,
        name: "SLO",
        addressing: AddressingMode::AbsoluteX,
        cycles: 7,
    },
    // Opcode: 0x20
    OpCode {
        execute: CPU::jsr,
        name: "JSR",
        addressing: AddressingMode::Absolute,
        cycles: 6,
    },
    // Opcode: 0x21
    OpCode {
        execute: CPU::and,
        name: "AND",
        addressing: AddressingMode::IndirectX,
        cycles: 6,
    },
    // Opcode: 0x21
    OpCode {
        execute: CPU::and,
        name: "AND",
        addressing: AddressingMode::IndirectX,
        cycles: 6,
    },
    // Opcode: 0x23
    OpCode {
        execute: CPU::rla,
        name: "RLA",
        addressing: AddressingMode::IndirectX,
        cycles: 8,
    },
    // Opcode: 0x24
    OpCode {
        execute: CPU::bit,
        name: "BIT",
        addressing: AddressingMode::ZeroPage,
        cycles: 3,
    },
    // Opcode: 0x25
    OpCode {
        execute: CPU::and,
        name: "AND",
        addressing: AddressingMode::ZeroPage,
        cycles: 3,
    },
    // Opcode: 0x26
    OpCode {
        execute: CPU::rol,
        name: "ROL",
        addressing: AddressingMode::ZeroPage,
        cycles: 5,
    },
    // Opcode: 0x27
    OpCode {
        execute: CPU::rla,
        name: "RLA",
        addressing: AddressingMode::ZeroPage,
        cycles: 5,
    },
    // Opcode: 0x28
    OpCode {
        execute: CPU::plp,
        name: "PLP",
        addressing: AddressingMode::Implied,
        cycles: 4,
    },
    // Opcode: 0x29
    OpCode {
        execute: CPU::and,
        name: "AND",
        addressing: AddressingMode::Immediate,
        cycles: 2,
    },
    // Opcode: 0x2A
    OpCode {
        execute: CPU::rol,
        name: "ROL",
        addressing: AddressingMode::Implied,
        cycles: 2,
    },
    // Opcode: 0x2B
    OpCode {
        execute: CPU::anc,
        name: "ANC",
        addressing: AddressingMode::Immediate,
        cycles: 2,
    },
    // Opcode: 0x2C
    OpCode {
        execute: CPU::bit,
        name: "BIT",
        addressing: AddressingMode::Absolute,
        cycles: 4,
    },
    // Opcode: 0x2D
    OpCode {
        execute: CPU::and,
        name: "AND",
        addressing: AddressingMode::Absolute,
        cycles: 4,
    },
    // Opcode: 0x2E
    OpCode {
        execute: CPU::rol,
        name: "ROL",
        addressing: AddressingMode::Absolute,
        cycles: 6,
    },
    // Opcode: 0x2F
    OpCode {
        execute: CPU::rla,
        name: "RLA",
        addressing: AddressingMode::Absolute,
        cycles: 6,
    },
    // Opcode: 0x30
    OpCode {
        execute: CPU::bmi,
        name: "BMI",
        addressing: AddressingMode::Relative,
        cycles: 2,
    },
    // Opcode: 0x31
    OpCode {
        execute: CPU::and,
        name: "AND",
        addressing: AddressingMode::IndirectY,
        cycles: 5,
    },
    // Opcode: 0x31
    OpCode {
        execute: CPU::and,
        name: "AND",
        addressing: AddressingMode::IndirectY,
        cycles: 5,
    },
    // Opcode: 0x33
    OpCode {
        execute: CPU::rla,
        name: "RLA",
        addressing: AddressingMode::IndirectY,
        cycles: 8,
    },
    // Opcode: 0x34
    OpCode {
        execute: CPU::nop,
        name: "NOP",
        addressing: AddressingMode::ZeroPageX,
        cycles: 4,
    },
    // Opcode: 0x35
    OpCode {
        execute: CPU::and,
        name: "AND",
        addressing: AddressingMode::ZeroPageX,
        cycles: 4,
    },
    // Opcode: 0x36
    OpCode {
        execute: CPU::rol,
        name: "ROL",
        addressing: AddressingMode::ZeroPageX,
        cycles: 6,
    },
    // Opcode: 0x37
    OpCode {
        execute: CPU::rla,
        name: "RLA",
        addressing: AddressingMode::ZeroPageX,
        cycles: 6,
    },
    // Opcode: 0x38
    OpCode {
        execute: CPU::sec,
        name: "SEC",
        addressing: AddressingMode::Implied,
        cycles: 2,
    },
    // Opcode: 0x39
    OpCode {
        execute: CPU::and,
        name: "AND",
        addressing: AddressingMode::AbsoluteY,
        cycles: 4,
    },
    // Opcode: 0x3A
    OpCode {
        execute: CPU::nop,
        name: "NOP",
        addressing: AddressingMode::Implied,
        cycles: 2,
    },
    // Opcode: 0x3B
    OpCode {
        execute: CPU::rla,
        name: "RLA",
        addressing: AddressingMode::AbsoluteY,
        cycles: 7,
    },
    // Opcode: 0x3C
    OpCode {
        execute: CPU::nop,
        name: "NOP",
        addressing: AddressingMode::AbsoluteX,
        cycles: 4,
    },
    // Opcode: 0x3D
    OpCode {
        execute: CPU::and,
        name: "AND",
        addressing: AddressingMode::AbsoluteX,
        cycles: 4,
    },
    // Opcode: 0x3E
    OpCode {
        execute: CPU::rol,
        name: "ROL",
        addressing: AddressingMode::AbsoluteX,
        cycles: 7,
    },
    // Opcode: 0x3F
    OpCode {
        execute: CPU::rla,
        name: "RLA",
        addressing: AddressingMode::AbsoluteX,
        cycles: 7,
    },
    // Opcode: 0x40
    OpCode {
        execute: CPU::rti,
        name: "RTI",
        addressing: AddressingMode::Implied,
        cycles: 6,
    },
    // Opcode: 0x41
    OpCode {
        execute: CPU::eor,
        name: "EOR",
        addressing: AddressingMode::IndirectX,
        cycles: 6,
    },
    // Opcode: 0x41
    OpCode {
        execute: CPU::eor,
        name: "EOR",
        addressing: AddressingMode::IndirectX,
        cycles: 6,
    },
    // Opcode: 0x43
    OpCode {
        execute: CPU::sre,
        name: "SRE",
        addressing: AddressingMode::IndirectX,
        cycles: 8,
    },
    // Opcode: 0x44
    OpCode {
        execute: CPU::nop,
        name: "NOP",
        addressing: AddressingMode::ZeroPage,
        cycles: 3,
    },
    // Opcode: 0x45
    OpCode {
        execute: CPU::eor,
        name: "EOR",
        addressing: AddressingMode::ZeroPage,
        cycles: 3,
    },
    // Opcode: 0x46
    OpCode {
        execute: CPU::lsr,
        name: "LSR",
        addressing: AddressingMode::ZeroPage,
        cycles: 5,
    },
    // Opcode: 0x47
    OpCode {
        execute: CPU::sre,
        name: "SRE",
        addressing: AddressingMode::ZeroPage,
        cycles: 5,
    },
    // Opcode: 0x48
    OpCode {
        execute: CPU::pha,
        name: "PHA",
        addressing: AddressingMode::Implied,
        cycles: 3,
    },
    // Opcode: 0x49
    OpCode {
        execute: CPU::eor,
        name: "EOR",
        addressing: AddressingMode::Immediate,
        cycles: 2,
    },
    // Opcode: 0x4A
    OpCode {
        execute: CPU::lsr,
        name: "LSR",
        addressing: AddressingMode::Implied,
        cycles: 2,
    },
    // Opcode: 0x4B
    OpCode {
        execute: CPU::alr,
        name: "ALR",
        addressing: AddressingMode::Immediate,
        cycles: 2,
    },
    // Opcode: 0x4C
    OpCode {
        execute: CPU::jmp,
        name: "JMP",
        addressing: AddressingMode::Absolute,
        cycles: 3,
    },
    // Opcode: 0x4D
    OpCode {
        execute: CPU::eor,
        name: "EOR",
        addressing: AddressingMode::Absolute,
        cycles: 4,
    },
    // Opcode: 0x4E
    OpCode {
        execute: CPU::lsr,
        name: "LSR",
        addressing: AddressingMode::Absolute,
        cycles: 6,
    },
    // Opcode: 0x4F
    OpCode {
        execute: CPU::sre,
        name: "SRE",
        addressing: AddressingMode::Absolute,
        cycles: 6,
    },
    // Opcode: 0x50
    OpCode {
        execute: CPU::bvc,
        name: "BVC",
        addressing: AddressingMode::Relative,
        cycles: 2,
    },
    // Opcode: 0x51
    OpCode {
        execute: CPU::eor,
        name: "EOR",
        addressing: AddressingMode::IndirectY,
        cycles: 5,
    },
    // Opcode: 0x51
    OpCode {
        execute: CPU::eor,
        name: "EOR",
        addressing: AddressingMode::IndirectY,
        cycles: 5,
    },
    // Opcode: 0x53
    OpCode {
        execute: CPU::sre,
        name: "SRE",
        addressing: AddressingMode::IndirectY,
        cycles: 8,
    },
    // Opcode: 0x54
    OpCode {
        execute: CPU::nop,
        name: "NOP",
        addressing: AddressingMode::ZeroPageX,
        cycles: 4,
    },
    // Opcode: 0x55
    OpCode {
        execute: CPU::eor,
        name: "EOR",
        addressing: AddressingMode::ZeroPageX,
        cycles: 4,
    },
    // Opcode: 0x56
    OpCode {
        execute: CPU::lsr,
        name: "LSR",
        addressing: AddressingMode::ZeroPageX,
        cycles: 6,
    },
    // Opcode: 0x57
    OpCode {
        execute: CPU::sre,
        name: "SRE",
        addressing: AddressingMode::ZeroPageX,
        cycles: 6,
    },
    // Opcode: 0x58
    OpCode {
        execute: CPU::cli,
        name: "CLI",
        addressing: AddressingMode::Implied,
        cycles: 2,
    },
    // Opcode: 0x59
    OpCode {
        execute: CPU::eor,
        name: "EOR",
        addressing: AddressingMode::AbsoluteY,
        cycles: 4,
    },
    // Opcode: 0x5A
    OpCode {
        execute: CPU::nop,
        name: "NOP",
        addressing: AddressingMode::Implied,
        cycles: 2,
    },
    // Opcode: 0x5B
    OpCode {
        execute: CPU::sre,
        name: "SRE",
        addressing: AddressingMode::AbsoluteY,
        cycles: 7,
    },
    // Opcode: 0x5C
    OpCode {
        execute: CPU::nop,
        name: "NOP",
        addressing: AddressingMode::AbsoluteX,
        cycles: 4,
    },
    // Opcode: 0x5D
    OpCode {
        execute: CPU::eor,
        name: "EOR",
        addressing: AddressingMode::AbsoluteX,
        cycles: 4,
    },
    // Opcode: 0x5E
    OpCode {
        execute: CPU::lsr,
        name: "LSR",
        addressing: AddressingMode::AbsoluteX,
        cycles: 7,
    },
    // Opcode: 0x5F
    OpCode {
        execute: CPU::sre,
        name: "SRE",
        addressing: AddressingMode::AbsoluteX,
        cycles: 7,
    },
    // Opcode: 0x60
    OpCode {
        execute: CPU::rts,
        name: "RTS",
        addressing: AddressingMode::Implied,
        cycles: 6,
    },
    // Opcode: 0x61
    OpCode {
        execute: CPU::adc,
        name: "ADC",
        addressing: AddressingMode::IndirectX,
        cycles: 6,
    },
    // Opcode: 0x61
    OpCode {
        execute: CPU::adc,
        name: "ADC",
        addressing: AddressingMode::IndirectX,
        cycles: 6,
    },
    // Opcode: 0x63
    OpCode {
        execute: CPU::rra,
        name: "RRA",
        addressing: AddressingMode::IndirectX,
        cycles: 8,
    },
    // Opcode: 0x64
    OpCode {
        execute: CPU::nop,
        name: "NOP",
        addressing: AddressingMode::ZeroPage,
        cycles: 3,
    },
    // Opcode: 0x65
    OpCode {
        execute: CPU::adc,
        name: "ADC",
        addressing: AddressingMode::ZeroPage,
        cycles: 3,
    },
    // Opcode: 0x66
    OpCode {
        execute: CPU::ror,
        name: "ROR",
        addressing: AddressingMode::ZeroPage,
        cycles: 5,
    },
    // Opcode: 0x67
    OpCode {
        execute: CPU::rra,
        name: "RRA",
        addressing: AddressingMode::ZeroPage,
        cycles: 5,
    },
    // Opcode: 0x68
    OpCode {
        execute: CPU::pla,
        name: "PLA",
        addressing: AddressingMode::Implied,
        cycles: 4,
    },
    // Opcode: 0x69
    OpCode {
        execute: CPU::adc,
        name: "ADC",
        addressing: AddressingMode::Immediate,
        cycles: 2,
    },
    // Opcode: 0x6A
    OpCode {
        execute: CPU::ror,
        name: "ROR",
        addressing: AddressingMode::Implied,
        cycles: 2,
    },
    // Opcode: 0x6B
    OpCode {
        execute: CPU::arr,
        name: "ARR",
        addressing: AddressingMode::Immediate,
        cycles: 2,
    },
    // Opcode: 0x6C
    OpCode {
        execute: CPU::jmp,
        name: "JMP",
        addressing: AddressingMode::Indirect,
        cycles: 5,
    },
    // Opcode: 0x6D
    OpCode {
        execute: CPU::adc,
        name: "ADC",
        addressing: AddressingMode::Absolute,
        cycles: 4,
    },
    // Opcode: 0x6E
    OpCode {
        execute: CPU::ror,
        name: "ROR",
        addressing: AddressingMode::Absolute,
        cycles: 6,
    },
    // Opcode: 0x6F
    OpCode {
        execute: CPU::rra,
        name: "RRA",
        addressing: AddressingMode::Absolute,
        cycles: 6,
    },
    // Opcode: 0x70
    OpCode {
        execute: CPU::bvs,
        name: "BVS",
        addressing: AddressingMode::Relative,
        cycles: 2,
    },
    // Opcode: 0x71
    OpCode {
        execute: CPU::adc,
        name: "ADC",
        addressing: AddressingMode::IndirectY,
        cycles: 5,
    },
    // Opcode: 0x71
    OpCode {
        execute: CPU::adc,
        name: "ADC",
        addressing: AddressingMode::IndirectY,
        cycles: 5,
    },
    // Opcode: 0x73
    OpCode {
        execute: CPU::rra,
        name: "RRA",
        addressing: AddressingMode::IndirectY,
        cycles: 8,
    },
    // Opcode: 0x74
    OpCode {
        execute: CPU::nop,
        name: "NOP",
        addressing: AddressingMode::ZeroPageX,
        cycles: 4,
    },
    // Opcode: 0x75
    OpCode {
        execute: CPU::adc,
        name: "ADC",
        addressing: AddressingMode::ZeroPageX,
        cycles: 4,
    },
    // Opcode: 0x76
    OpCode {
        execute: CPU::ror,
        name: "ROR",
        addressing: AddressingMode::ZeroPageX,
        cycles: 6,
    },
    // Opcode: 0x77
    OpCode {
        execute: CPU::rra,
        name: "RRA",
        addressing: AddressingMode::ZeroPageX,
        cycles: 6,
    },
    // Opcode: 0x78
    OpCode {
        execute: CPU::sei,
        name: "SEI",
        addressing: AddressingMode::Implied,
        cycles: 2,
    },
    // Opcode: 0x79
    OpCode {
        execute: CPU::adc,
        name: "ADC",
        addressing: AddressingMode::AbsoluteY,
        cycles: 4,
    },
    // Opcode: 0x7A
    OpCode {
        execute: CPU::nop,
        name: "NOP",
        addressing: AddressingMode::Implied,
        cycles: 2,
    },
    // Opcode: 0x7B
    OpCode {
        execute: CPU::rra,
        name: "RRA",
        addressing: AddressingMode::AbsoluteY,
        cycles: 7,
    },
    // Opcode: 0x7C
    OpCode {
        execute: CPU::nop,
        name: "NOP",
        addressing: AddressingMode::AbsoluteX,
        cycles: 4,
    },
    // Opcode: 0x7D
    OpCode {
        execute: CPU::adc,
        name: "ADC",
        addressing: AddressingMode::AbsoluteX,
        cycles: 4,
    },
    // Opcode: 0x7E
    OpCode {
        execute: CPU::ror,
        name: "ROR",
        addressing: AddressingMode::AbsoluteX,
        cycles: 7,
    },
    // Opcode: 0x7F
    OpCode {
        execute: CPU::rra,
        name: "RRA",
        addressing: AddressingMode::AbsoluteX,
        cycles: 7,
    },
    // Opcode: 0x80
    OpCode {
        execute: CPU::nop,
        name: "NOP",
        addressing: AddressingMode::Immediate,
        cycles: 2,
    },
    // Opcode: 0x81
    OpCode {
        execute: CPU::sta,
        name: "STA",
        addressing: AddressingMode::IndirectX,
        cycles: 6,
    },
    // Opcode: 0x82
    OpCode {
        execute: CPU::nop,
        name: "NOP",
        addressing: AddressingMode::Immediate,
        cycles: 2,
    },
    // Opcode: 0x83
    OpCode {
        execute: CPU::sax,
        name: "SAX",
        addressing: AddressingMode::IndirectX,
        cycles: 6,
    },
    // Opcode: 0x84
    OpCode {
        execute: CPU::sty,
        name: "STY",
        addressing: AddressingMode::ZeroPage,
        cycles: 3,
    },
    // Opcode: 0x85
    OpCode {
        execute: CPU::sta,
        name: "STA",
        addressing: AddressingMode::ZeroPage,
        cycles: 3,
    },
    // Opcode: 0x86
    OpCode {
        execute: CPU::stx,
        name: "STX",
        addressing: AddressingMode::ZeroPage,
        cycles: 3,
    },
    // Opcode: 0x87
    OpCode {
        execute: CPU::sax,
        name: "SAX",
        addressing: AddressingMode::ZeroPage,
        cycles: 3,
    },
    // Opcode: 0x88
    OpCode {
        execute: CPU::dey,
        name: "DEY",
        addressing: AddressingMode::Implied,
        cycles: 2,
    },
    // Opcode: 0x89
    OpCode {
        execute: CPU::nop,
        name: "NOP",
        addressing: AddressingMode::Immediate,
        cycles: 2,
    },
    // Opcode: 0x8A
    OpCode {
        execute: CPU::txa,
        name: "TXA",
        addressing: AddressingMode::Implied,
        cycles: 2,
    },
    // Opcode: 0x8B
    OpCode {
        execute: CPU::xaa,
        name: "XAA",
        addressing: AddressingMode::Immediate,
        cycles: 2,
    },
    // Opcode: 0x8C
    OpCode {
        execute: CPU::sty,
        name: "STY",
        addressing: AddressingMode::Absolute,
        cycles: 4,
    },
    // Opcode: 0x8D
    OpCode {
        execute: CPU::sta,
        name: "STA",
        addressing: AddressingMode::Absolute,
        cycles: 4,
    },
    // Opcode: 0x8E
    OpCode {
        execute: CPU::stx,
        name: "STX",
        addressing: AddressingMode::Absolute,
        cycles: 4,
    },
    // Opcode: 0x8F
    OpCode {
        execute: CPU::sax,
        name: "SAX",
        addressing: AddressingMode::Absolute,
        cycles: 4,
    },
    // Opcode: 0x90
    OpCode {
        execute: CPU::bcc,
        name: "BCC",
        addressing: AddressingMode::Relative,
        cycles: 2,
    },
    // Opcode: 0x91
    OpCode {
        execute: CPU::sta,
        name: "STA",
        addressing: AddressingMode::IndirectY,
        cycles: 6,
    },
    // Opcode: 0x91
    OpCode {
        execute: CPU::sta,
        name: "STA",
        addressing: AddressingMode::IndirectY,
        cycles: 6,
    },
    // Opcode: 0x93
    OpCode {
        execute: CPU::ahx,
        name: "AHX",
        addressing: AddressingMode::IndirectY,
        cycles: 6,
    },
    // Opcode: 0x94
    OpCode {
        execute: CPU::sty,
        name: "STY",
        addressing: AddressingMode::ZeroPageX,
        cycles: 4,
    },
    // Opcode: 0x95
    OpCode {
        execute: CPU::sta,
        name: "STA",
        addressing: AddressingMode::ZeroPageX,
        cycles: 4,
    },
    // Opcode: 0x96
    OpCode {
        execute: CPU::stx,
        name: "STX",
        addressing: AddressingMode::ZeroPageY,
        cycles: 4,
    },
    // Opcode: 0x97
    OpCode {
        execute: CPU::sax,
        name: "SAX",
        addressing: AddressingMode::ZeroPageY,
        cycles: 4,
    },
    // Opcode: 0x98
    OpCode {
        execute: CPU::tya,
        name: "TYA",
        addressing: AddressingMode::Implied,
        cycles: 2,
    },
    // Opcode: 0x99
    OpCode {
        execute: CPU::sta,
        name: "STA",
        addressing: AddressingMode::AbsoluteY,
        cycles: 5,
    },
    // Opcode: 0x9A
    OpCode {
        execute: CPU::txs,
        name: "TXS",
        addressing: AddressingMode::Implied,
        cycles: 2,
    },
    // Opcode: 0x9B
    OpCode {
        execute: CPU::tas,
        name: "TAS",
        addressing: AddressingMode::AbsoluteY,
        cycles: 5,
    },
    // Opcode: 0x9C
    OpCode {
        execute: CPU::shy,
        name: "SHY",
        addressing: AddressingMode::AbsoluteX,
        cycles: 5,
    },
    // Opcode: 0x9D
    OpCode {
        execute: CPU::sta,
        name: "STA",
        addressing: AddressingMode::AbsoluteX,
        cycles: 5,
    },
    // Opcode: 0x9E
    OpCode {
        execute: CPU::shx,
        name: "SHX",
        addressing: AddressingMode::AbsoluteY,
        cycles: 5,
    },
    // Opcode: 0x9F
    OpCode {
        execute: CPU::ahx,
        name: "AHX",
        addressing: AddressingMode::AbsoluteY,
        cycles: 5,
    },
    // Opcode: 0xA0
    OpCode {
        execute: CPU::ldy,
        name: "LDY",
        addressing: AddressingMode::Immediate,
        cycles: 2,
    },
    // Opcode: 0xA1
    OpCode {
        execute: CPU::lda,
        name: "LDA",
        addressing: AddressingMode::IndirectX,
        cycles: 6,
    },
    // Opcode: 0xA2
    OpCode {
        execute: CPU::ldx,
        name: "LDX",
        addressing: AddressingMode::Immediate,
        cycles: 2,
    },
    // Opcode: 0xA3
    OpCode {
        execute: CPU::lax,
        name: "LAX",
        addressing: AddressingMode::IndirectX,
        cycles: 6,
    },
    // Opcode: 0xA4
    OpCode {
        execute: CPU::ldy,
        name: "LDY",
        addressing: AddressingMode::ZeroPage,
        cycles: 3,
    },
    // Opcode: 0xA5
    OpCode {
        execute: CPU::lda,
        name: "LDA",
        addressing: AddressingMode::ZeroPage,
        cycles: 3,
    },
    // Opcode: 0xA6
    OpCode {
        execute: CPU::ldx,
        name: "LDX",
        addressing: AddressingMode::ZeroPage,
        cycles: 3,
    },
    // Opcode: 0xA7
    OpCode {
        execute: CPU::lax,
        name: "LAX",
        addressing: AddressingMode::ZeroPage,
        cycles: 3,
    },
    // Opcode: 0xA8
    OpCode {
        execute: CPU::tay,
        name: "TAY",
        addressing: AddressingMode::Implied,
        cycles: 2,
    },
    // Opcode: 0xA9
    OpCode {
        execute: CPU::lda,
        name: "LDA",
        addressing: AddressingMode::Immediate,
        cycles: 2,
    },
    // Opcode: 0xAA
    OpCode {
        execute: CPU::tax,
        name: "TAX",
        addressing: AddressingMode::Implied,
        cycles: 2,
    },
    // Opcode: 0xAB
    OpCode {
        execute: CPU::lax,
        name: "LAX",
        addressing: AddressingMode::Immediate,
        cycles: 2,
    },
    // Opcode: 0xAC
    OpCode {
        execute: CPU::ldy,
        name: "LDY",
        addressing: AddressingMode::Absolute,
        cycles: 4,
    },
    // Opcode: 0xAD
    OpCode {
        execute: CPU::lda,
        name: "LDA",
        addressing: AddressingMode::Absolute,
        cycles: 4,
    },
    // Opcode: 0xAE
    OpCode {
        execute: CPU::ldx,
        name: "LDX",
        addressing: AddressingMode::Absolute,
        cycles: 4,
    },
    // Opcode: 0xAF
    OpCode {
        execute: CPU::lax,
        name: "LAX",
        addressing: AddressingMode::Absolute,
        cycles: 4,
    },
    // Opcode: 0xB0
    OpCode {
        execute: CPU::bcs,
        name: "BCS",
        addressing: AddressingMode::Relative,
        cycles: 2,
    },
    // Opcode: 0xB1
    OpCode {
        execute: CPU::lda,
        name: "LDA",
        addressing: AddressingMode::IndirectY,
        cycles: 5,
    },
    // Opcode: 0xB1
    OpCode {
        execute: CPU::lda,
        name: "LDA",
        addressing: AddressingMode::IndirectY,
        cycles: 5,
    },
    // Opcode: 0xB3
    OpCode {
        execute: CPU::lax,
        name: "LAX",
        addressing: AddressingMode::IndirectY,
        cycles: 5,
    },
    // Opcode: 0xB4
    OpCode {
        execute: CPU::ldy,
        name: "LDY",
        addressing: AddressingMode::ZeroPageX,
        cycles: 4,
    },
    // Opcode: 0xB5
    OpCode {
        execute: CPU::lda,
        name: "LDA",
        addressing: AddressingMode::ZeroPageX,
        cycles: 4,
    },
    // Opcode: 0xB6
    OpCode {
        execute: CPU::ldx,
        name: "LDX",
        addressing: AddressingMode::ZeroPageY,
        cycles: 4,
    },
    // Opcode: 0xB7
    OpCode {
        execute: CPU::lax,
        name: "LAX",
        addressing: AddressingMode::ZeroPageY,
        cycles: 4,
    },
    // Opcode: 0xB8
    OpCode {
        execute: CPU::clv,
        name: "CLV",
        addressing: AddressingMode::Implied,
        cycles: 2,
    },
    // Opcode: 0xB9
    OpCode {
        execute: CPU::lda,
        name: "LDA",
        addressing: AddressingMode::AbsoluteY,
        cycles: 4,
    },
    // Opcode: 0xBA
    OpCode {
        execute: CPU::tsx,
        name: "TSX",
        addressing: AddressingMode::Implied,
        cycles: 2,
    },
    // Opcode: 0xBB
    OpCode {
        execute: CPU::las,
        name: "LAS",
        addressing: AddressingMode::AbsoluteY,
        cycles: 4,
    },
    // Opcode: 0xBC
    OpCode {
        execute: CPU::ldy,
        name: "LDY",
        addressing: AddressingMode::AbsoluteX,
        cycles: 4,
    },
    // Opcode: 0xBD
    OpCode {
        execute: CPU::lda,
        name: "LDA",
        addressing: AddressingMode::AbsoluteX,
        cycles: 4,
    },
    // Opcode: 0xBE
    OpCode {
        execute: CPU::ldx,
        name: "LDX",
        addressing: AddressingMode::AbsoluteY,
        cycles: 4,
    },
    // Opcode: 0xBF
    OpCode {
        execute: CPU::lax,
        name: "LAX",
        addressing: AddressingMode::AbsoluteY,
        cycles: 4,
    },
    // Opcode: 0xC0
    OpCode {
        execute: CPU::cpy,
        name: "CPY",
        addressing: AddressingMode::Immediate,
        cycles: 2,
    },
    // Opcode: 0xC1
    OpCode {
        execute: CPU::cmp,
        name: "CMP",
        addressing: AddressingMode::IndirectX,
        cycles: 6,
    },
    // Opcode: 0xC2
    OpCode {
        execute: CPU::nop,
        name: "NOP",
        addressing: AddressingMode::Immediate,
        cycles: 2,
    },
    // Opcode: 0xC3
    OpCode {
        execute: CPU::dcp,
        name: "DCP",
        addressing: AddressingMode::IndirectX,
        cycles: 8,
    },
    // Opcode: 0xC4
    OpCode {
        execute: CPU::cpy,
        name: "CPY",
        addressing: AddressingMode::ZeroPage,
        cycles: 3,
    },
    // Opcode: 0xC5
    OpCode {
        execute: CPU::cmp,
        name: "CMP",
        addressing: AddressingMode::ZeroPage,
        cycles: 3,
    },
    // Opcode: 0xC6
    OpCode {
        execute: CPU::dec,
        name: "DEC",
        addressing: AddressingMode::ZeroPage,
        cycles: 5,
    },
    // Opcode: 0xC7
    OpCode {
        execute: CPU::dcp,
        name: "DCP",
        addressing: AddressingMode::ZeroPage,
        cycles: 5,
    },
    // Opcode: 0xC8
    OpCode {
        execute: CPU::iny,
        name: "INY",
        addressing: AddressingMode::Implied,
        cycles: 2,
    },
    // Opcode: 0xC9
    OpCode {
        execute: CPU::cmp,
        name: "CMP",
        addressing: AddressingMode::Immediate,
        cycles: 2,
    },
    // Opcode: 0xCA
    OpCode {
        execute: CPU::dex,
        name: "DEX",
        addressing: AddressingMode::Implied,
        cycles: 2,
    },
    // Opcode: 0xCB
    OpCode {
        execute: CPU::axs,
        name: "AXS",
        addressing: AddressingMode::Immediate,
        cycles: 2,
    },
    // Opcode: 0xCC
    OpCode {
        execute: CPU::cpy,
        name: "CPY",
        addressing: AddressingMode::Absolute,
        cycles: 4,
    },
    // Opcode: 0xCD
    OpCode {
        execute: CPU::cmp,
        name: "CMP",
        addressing: AddressingMode::Absolute,
        cycles: 4,
    },
    // Opcode: 0xCE
    OpCode {
        execute: CPU::dec,
        name: "DEC",
        addressing: AddressingMode::Absolute,
        cycles: 6,
    },
    // Opcode: 0xCF
    OpCode {
        execute: CPU::dcp,
        name: "DCP",
        addressing: AddressingMode::Absolute,
        cycles: 6,
    },
    // Opcode: 0xD0
    OpCode {
        execute: CPU::bne,
        name: "BNE",
        addressing: AddressingMode::Relative,
        cycles: 2,
    },
    // Opcode: 0xD1
    OpCode {
        execute: CPU::cmp,
        name: "CMP",
        addressing: AddressingMode::IndirectY,
        cycles: 5,
    },
    // Opcode: 0xD1
    OpCode {
        execute: CPU::cmp,
        name: "CMP",
        addressing: AddressingMode::IndirectY,
        cycles: 5,
    },
    // Opcode: 0xD3
    OpCode {
        execute: CPU::dcp,
        name: "DCP",
        addressing: AddressingMode::IndirectY,
        cycles: 8,
    },
    // Opcode: 0xD4
    OpCode {
        execute: CPU::nop,
        name: "NOP",
        addressing: AddressingMode::ZeroPageX,
        cycles: 4,
    },
    // Opcode: 0xD5
    OpCode {
        execute: CPU::cmp,
        name: "CMP",
        addressing: AddressingMode::ZeroPageX,
        cycles: 4,
    },
    // Opcode: 0xD6
    OpCode {
        execute: CPU::dec,
        name: "DEC",
        addressing: AddressingMode::ZeroPageX,
        cycles: 6,
    },
    // Opcode: 0xD7
    OpCode {
        execute: CPU::dcp,
        name: "DCP",
        addressing: AddressingMode::ZeroPageX,
        cycles: 6,
    },
    // Opcode: 0xD8
    OpCode {
        execute: CPU::cld,
        name: "CLD",
        addressing: AddressingMode::Implied,
        cycles: 2,
    },
    // Opcode: 0xD9
    OpCode {
        execute: CPU::cmp,
        name: "CMP",
        addressing: AddressingMode::AbsoluteY,
        cycles: 4,
    },
    // Opcode: 0xDA
    OpCode {
        execute: CPU::nop,
        name: "NOP",
        addressing: AddressingMode::Implied,
        cycles: 2,
    },
    // Opcode: 0xDB
    OpCode {
        execute: CPU::dcp,
        name: "DCP",
        addressing: AddressingMode::AbsoluteY,
        cycles: 7,
    },
    // Opcode: 0xDC
    OpCode {
        execute: CPU::nop,
        name: "NOP",
        addressing: AddressingMode::AbsoluteX,
        cycles: 4,
    },
    // Opcode: 0xDD
    OpCode {
        execute: CPU::cmp,
        name: "CMP",
        addressing: AddressingMode::AbsoluteX,
        cycles: 4,
    },
    // Opcode: 0xDE
    OpCode {
        execute: CPU::dec,
        name: "DEC",
        addressing: AddressingMode::AbsoluteX,
        cycles: 7,
    },
    // Opcode: 0xDF
    OpCode {
        execute: CPU::dcp,
        name: "DCP",
        addressing: AddressingMode::AbsoluteX,
        cycles: 7,
    },
    // Opcode: 0xE0
    OpCode {
        execute: CPU::cpx,
        name: "CPX",
        addressing: AddressingMode::Immediate,
        cycles: 2,
    },
    // Opcode: 0xE1
    OpCode {
        execute: CPU::sbc,
        name: "SBC",
        addressing: AddressingMode::IndirectX,
        cycles: 6,
    },
    // Opcode: 0xE2
    OpCode {
        execute: CPU::nop,
        name: "NOP",
        addressing: AddressingMode::Immediate,
        cycles: 2,
    },
    // Opcode: 0xE3
    OpCode {
        execute: CPU::isc,
        name: "ISC",
        addressing: AddressingMode::IndirectX,
        cycles: 8,
    },
    // Opcode: 0xE4
    OpCode {
        execute: CPU::cpx,
        name: "CPX",
        addressing: AddressingMode::ZeroPage,
        cycles: 3,
    },
    // Opcode: 0xE5
    OpCode {
        execute: CPU::sbc,
        name: "SBC",
        addressing: AddressingMode::ZeroPage,
        cycles: 3,
    },
    // Opcode: 0xE6
    OpCode {
        execute: CPU::inc,
        name: "INC",
        addressing: AddressingMode::ZeroPage,
        cycles: 5,
    },
    // Opcode: 0xE7
    OpCode {
        execute: CPU::isc,
        name: "ISC",
        addressing: AddressingMode::ZeroPage,
        cycles: 5,
    },
    // Opcode: 0xE8
    OpCode {
        execute: CPU::inx,
        name: "INX",
        addressing: AddressingMode::Implied,
        cycles: 2,
    },
    // Opcode: 0xE9
    OpCode {
        execute: CPU::sbc,
        name: "SBC",
        addressing: AddressingMode::Immediate,
        cycles: 2,
    },
    // Opcode: 0xEA
    OpCode {
        execute: CPU::nop,
        name: "NOP",
        addressing: AddressingMode::Implied,
        cycles: 2,
    },
    // Opcode: 0xEB
    OpCode {
        execute: CPU::sbc,
        name: "SBC",
        addressing: AddressingMode::Immediate,
        cycles: 2,
    },
    // Opcode: 0xEC
    OpCode {
        execute: CPU::cpx,
        name: "CPX",
        addressing: AddressingMode::Absolute,
        cycles: 4,
    },
    // Opcode: 0xED
    OpCode {
        execute: CPU::sbc,
        name: "SBC",
        addressing: AddressingMode::Absolute,
        cycles: 4,
    },
    // Opcode: 0xEE
    OpCode {
        execute: CPU::inc,
        name: "INC",
        addressing: AddressingMode::Absolute,
        cycles: 6,
    },
    // Opcode: 0xEF
    OpCode {
        execute: CPU::isc,
        name: "ISC",
        addressing: AddressingMode::Absolute,
        cycles: 6,
    },
    // Opcode: 0xF0
    OpCode {
        execute: CPU::beq,
        name: "BEQ",
        addressing: AddressingMode::Relative,
        cycles: 2,
    },
    // Opcode: 0xF1
    OpCode {
        execute: CPU::sbc,
        name: "SBC",
        addressing: AddressingMode::IndirectY,
        cycles: 5,
    },
    // Opcode: 0xF1
    OpCode {
        execute: CPU::sbc,
        name: "SBC",
        addressing: AddressingMode::IndirectY,
        cycles: 5,
    },
    // Opcode: 0xF3
    OpCode {
        execute: CPU::isc,
        name: "ISC",
        addressing: AddressingMode::IndirectY,
        cycles: 8,
    },
    // Opcode: 0xF4
    OpCode {
        execute: CPU::nop,
        name: "NOP",
        addressing: AddressingMode::ZeroPageX,
        cycles: 4,
    },
    // Opcode: 0xF5
    OpCode {
        execute: CPU::sbc,
        name: "SBC",
        addressing: AddressingMode::ZeroPageX,
        cycles: 4,
    },
    // Opcode: 0xF6
    OpCode {
        execute: CPU::inc,
        name: "INC",
        addressing: AddressingMode::ZeroPageX,
        cycles: 6,
    },
    // Opcode: 0xF7
    OpCode {
        execute: CPU::isc,
        name: "ISC",
        addressing: AddressingMode::ZeroPageX,
        cycles: 6,
    },
    // Opcode: 0xF8
    OpCode {
        execute: CPU::sed,
        name: "SED",
        addressing: AddressingMode::Implied,
        cycles: 2,
    },
    // Opcode: 0xF9
    OpCode {
        execute: CPU::sbc,
        name: "SBC",
        addressing: AddressingMode::AbsoluteY,
        cycles: 4,
    },
    // Opcode: 0xFA
    OpCode {
        execute: CPU::nop,
        name: "NOP",
        addressing: AddressingMode::Implied,
        cycles: 2,
    },
    // Opcode: 0xFB
    OpCode {
        execute: CPU::isc,
        name: "ISC",
        addressing: AddressingMode::AbsoluteY,
        cycles: 7,
    },
    // Opcode: 0xFC
    OpCode {
        execute: CPU::nop,
        name: "NOP",
        addressing: AddressingMode::AbsoluteX,
        cycles: 4,
    },
    // Opcode: 0xFD
    OpCode {
        execute: CPU::sbc,
        name: "SBC",
        addressing: AddressingMode::AbsoluteX,
        cycles: 4,
    },
    // Opcode: 0xFE
    OpCode {
        execute: CPU::inc,
        name: "INC",
        addressing: AddressingMode::AbsoluteX,
        cycles: 7,
    },
    // Opcode: 0xFF
    OpCode {
        execute: CPU::isc,
        name: "ISC",
        addressing: AddressingMode::AbsoluteX,
        cycles: 7,
    },
];
